/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Active': '激活',
    'Age': '年龄:\t',
    'Beggar': '乞丐',
    'Beggar lvl': '乞丐等级',
    'House': '房子',
    'Holy knight': '圣骑士',
    'Import': '导入',
    'Import/export save': '导入/导出存档',
    'Farmer': '农民',
    'Export': '导出',
    'Evil': '邪恶',
    'Evil control': '邪恶控制',
    'Expense/day': '费用/天',
    'years': '年',
    'Xp/day': '经验/天',
    'xp multipliers': '经验加成',
    'Xp left': '经验剩余',
    'Level': '等级',
    'Library': '图书馆',
    'Mage': '法师',
    'Lifespan': '寿命',
    'Magic': '魔法',
    'Mana control': '法力控制',
    'Max level': '最高级',
    'Miner': '矿工',
    'Misc': '杂项',
    'Jobs': '工作',
    'Skills': '技能',
    'Shop': '商店',
    'Play': '继续',
    'Pause': '暂停',
    'Personal squire': '私人护卫',
    'Required: ': '要求: ',
    'Reset': '重置',
    'Sapphire charm': '蓝宝石护符',
    'Settings': '设置',
    'Skip': '跳过',
    'Squire': '护卫',
    'Student': '学生',
    'Steel longsword': '钢长剑',
    'Study desk': '书桌',
    'Task': '任务',
    'Toggle': '切换',
    'Touch the eye': '触摸眼球',
    'Wizard': '巫师',
    'Wooden hut': '木屋',
    'Properties': '属性',
    'Progress Knight': '骑士进度条',
    'Small palace': '小宫殿',
    'Strength': '力量',
    'Tent': '帐篷',
    'The Arcane Association': '奥术协会',
    'Veteran footman': '资深步兵',
    'Veteran knight': '资深骑士',
    'Toggle light/dark mode': '切换亮/暗模式',
    'Time warping': '时间扭曲',
    'Amulet': '护身符',
    'Age has caught up to you': '年龄已经赶上了你',
    'Apprentice mage': '魔法学徒',
    'Auto-learn': '自动学习',
    'Auto-promote': '自动提升',
    'Book': '书',
    'Chairman': '会长',
    'Combat': '战斗',
    'Cottage': '茅屋',
    'Current job': '当前工作',
    'Current skill': '当前技能',
    'Dark magic': '黑暗魔法',
    'Super immortality': '超级永生',
    'Net/day': '净/天',
    'Muscle memory': '肌肉记忆',
    'Military': '军队',
    'Merchant': '商人',
    'Meditation': '冥想',
    'Large house': '大房子',
    'Knight': '骑士',
    'Join the discord community!': '加入discord社区！',
    'Intimidation': '威胁',
    'Immortality': '永生',
    'Income/day': '收入/天',
    'Homeless': '无家可归',
    'Hard reset game': '硬重置',
    'Grand palace': '大型宫殿',
    'Fundamentals': '基本原理',
    'Elite knight': '精英骑士',
    'Effect': '效果',
    'Dumbbells': '哑铃',
    'Day': '天',
    'Dark influence': '黑暗影响',
    'Demon training': '魔鬼训练',
    'Disable warp': '禁用扭曲',
    'Common work': '常规工作',
    'Butler': '步兵',
    'Blood meditation': '血之冥想',
    'Concentration': '专注',
    'Bargaining': '讨价还价',
    'Battle tactics': '战斗战术',
    'Blacksmith': '铁匠',
    'Affects game speed': '影响游戏速度',
    'Affects dark magic xp gain': '影响黑魔法经验收益',
    'Affects all xp gain': '影响所有经验收益',
    'Concentration lvl': '专注等级',
    'evil': '邪恶',
    'Fisherman': '渔夫',
    'Footman': '步兵',
    'Happiness': '幸福',
    'Balance (in coins': '余额 (以硬币计',
    'Legendary knight': '传奇骑士',
    'Farmer lvl': '农民等级',
    'Enable warp': '启用扭曲',
    'Embrace evil': '拥抱邪恶',
    'Demon\'s wealth': '恶魔的财富',
    'Obliterate squadrons of enemy soldiers in one go with extraordinary proficiency, while equipped with the finest gear. Such a feared unit on the battlefield is paid extremely well.': '用最精良的装备，一次歼灭敌军中队。这样一支令人敬畏的部队在战场上的薪水非常高。',
    'Much larger than a regular house, which boasts even more rooms and multiple floors. The building is quite spacious but comes with a hefty price tag.': '比普通的房子大得多，普通的房子有更多的房间和多层。这栋建筑很宽敞，但价格不菲。',
    'Lengthen your lifespan through the means of magic. However, is this truly the immortality you have tried seeking for...?': '用魔法延长你的寿命。然而，这真的是你一直在寻找的永生吗?',
    'Create and revise battle strategies, improving experience gained in the military.': '创建和修改作战策略，提高在军队中获得的经验。',
    'Condition your body and strength through harsh training. Stronger individuals are paid more in the military.': '通过艰苦的训练来调节你的身体和力量。更强壮的人在军队中得到更多的报酬。',
    'Collapse entire armies in mere seconds with your magically imbued blade. The handful of elite knights who attain this level of power are showered with coins.': '用你的魔法剑在几秒钟内瓦解整个军队。少数精英骑士获得这个等级的权力会得到大量的金币。',
    'Carry around your knight\'s shield and sword along the battlefield. Very meager pay but the work experience is quite valuable.': '带着你骑士的盾牌和剑沿着战场行进。工资很低，但工作经验很有价值。',
    'Plow the fields and grow the crops. It\'s not much but it\'s honest work.': '犁地，种庄稼。这工作不多，但很正经。',
    ', which will heavily impact your future lives.': '，这将严重影响你们未来的生活。',
    'Delve into dangerous caverns and mine valuable ores. The pay is quite meager compared to the risk involved.': '深入危险的洞穴，开采有价值的矿石。与所涉及的风险相比，报酬是相当少的。',
    'Encompass yourself with formidable power bestowed upon you by evil, allowing you to pick up and absorb any job or skill with ease.': '用邪恶赋予你的强大力量包围你自己，让你轻松地获得和吸收任何工作或技能。',
    'Embedded with a rare sapphire, this charm activates more mana channels within your body, providing a much easier time learning magic.': '镶嵌在一颗罕见的蓝宝石上，这个咒语激活你体内更多的魔法通道，让你更容易学习魔法。',
    'Grow and culture the evil within you through the sacrifise of other living beings, drastically increasing evil gain.': '通过其他生物的牺牲来成长和培养你内在的邪恶，急剧增加邪恶收益。',
    'Heavy tools used in strenuous exercise to toughen up and accumulate strength even faster than before.': '在剧烈运动中用来比以前更快地增强和积累力量的重型工具。',
    'Keeps your household clean at all times and also prepares three delicious meals per day, leaving you in a happier, stress-free mood.': '让你的家庭随时保持清洁，每天还准备三顿美味的饭菜，让你在一个更幸福，无压力的心情。',
    'Learn to emit a devilish aura which strikes extreme fear into other merchants, forcing them to give you heavy discounts.': '学会散发一种恶魔的气息，打击其他商家的极度恐惧，迫使他们给你很大的折扣。',
    'Learn to procrastinate less at work and receive more job experience per day.': '学会在工作中减少拖延，每天积累更多的工作经验。',
    'Productivity': '效率',
    'Put down your life to battle with enemy soldiers. A courageous, respectable job but you are still worthless in the grand scheme of things.': '放下你的生命与敌人的士兵战斗。一份勇敢，体面的工作但你在这个宏伟的计划中仍然毫无价值。',
    'Reel in various fish and sell them for a handful of coins. A relaxing but still a poor paying job.': '钓上各种各样的鱼，然后把它们卖成一把硬币。一份轻松但收入微薄的工作。',
    'Shabby logs and dirty hay glued together with horse manure. Much more sturdy than a tent, however, the stench isn\'t very pleasant.': '破烂的原木和肮脏的干草和马粪粘在一起。虽然比帐篷坚固多了，但是臭气也不太好闻。',
    'Slash and pierce through enemy soldiers with ease, while covered in steel from head to toe. A decently paying and very respectable job.': '从头到脚都裹着钢铁，轻松地刺穿敌军士兵。一份报酬丰厚、非常体面的工作。',
    'Sleep on the uncomfortable, filthy streets while almost freezing to death every night. It cannot get any worse than this.': '睡在不舒服、肮脏的街道上，每天晚上几乎冻死。不会比这更糟了。',
    'Smelt ores and carefully forge weapons for the military. A respectable and OK paying commoner job.': '为军队冶炼矿石，精心锻造武器。一份体面的、报酬不错的普通工作。',
    'Something tells you that the amulet might transform even further after living for': '直觉告诉你，在你完成了第一次重生之后，如果你的年龄（当前年龄，不是寿命上限）超过200岁，这个护身符还可能会带来更大的变化',
    'Spend your days administrating The Arcane Association and investigate the concepts of true immortality. The chairman receives ludicrous amounts of pay daily.': '花时间管理你的神秘协会和调查的概念，真正的永生。会长每天收到的薪水多得可笑。',
    'Study the theory of mana and practice basic spells. There is minor pay to cover living costs, however, this is a necessary stage in becoming a mage.': '学习法术力理论并练习基本法术。 可以支付生活费用的少量薪水，但是，这是成为法师的必经阶段。',
    'Struggle day and night for a couple of copper coins. It feels like you are at the brink of death each day.': '昼夜不停地挣扎着几个铜币。 感觉就像您每天都处在死亡边缘。',
    'Strengthen your neurons through habit and repetition, improving strength gains throughout the body.': '通过习惯和重复来强化你的神经元，改善全身力量的增强。',
    'Structured with a timber frame and a thatched roof. Provides decent living conditions for a fair price.': '用木框架和茅草屋顶建造的。以公平的价格提供体面的生活条件。',
    'Strengthen your mana channels throughout your body, aiding you in becoming a more powerful magical user.': '加强你全身的魔法通道，帮助你成为一个更强大的魔法使用者。',
    'Stores a collection of books, each containing vast amounts of information from basic life skills to complex magic spells.': '储存了大量的书籍，每一本都包含了大量的信息，从基本的生活技能到复杂的魔法咒语。',
    'for your jobs and skills equivalent to': '对你的工作和技能，加成的公式为',
    'Fill your mind with peace and tranquility to tap into greater happiness from within.': '让你的头脑充满和平与安宁，从内心发掘更大的幸福。',
    'Feared worldwide, obliterate entire nations in a blink of an eye. Roughly every century, only one holy knight is worthy of receiving such an esteemed title.': '让全世界都感到恐惧，一眨眼的功夫就把整个国家都毁灭了。大约每个世纪，只有一位神圣骑士配得上这样一个受人尊敬的头衔。',
    'A grand residence completely composed of gold and silver. Provides the utmost luxurious and comfortable living conditions possible for a ludicrous price.': '一座完全由金银构成的宏伟住宅。以可笑的价格提供最豪华和舒适的生活条件。',
    'A fine blade used to slay enemies even quicker in combat and therefore gain more experience.': '在战斗中可以更快地杀死敌人，从而获得更多经验。',
    'A mere human body is too feeble and weak to withstand evil. Train with forbidden methods to slowly manifest into a demon, capable of absorbing knowledge rapidly.': '仅仅是人的身体就太软弱无力，无法抵挡邪恶。用禁止的方法训练，慢慢变成一个能够快速吸收知识的恶魔。',
    'A place to write down all your thoughts and discoveries, allowing you to learn a lot more quickly.': '一个写下你所有想法和发现的地方，让你学得更快。',
    'A thin sheet of tattered cloth held up by a couple of feeble, wooden sticks. Horrible living conditions but at least you have a roof over your head.': '一张由两根软弱的木棒托着的破布。生活条件很糟糕，但至少你有个栖身之所。',
    'A very rich and meticulously built structure rimmed with fine metals such as silver. Extremely high expenses to maintain for a lavish lifestyle.': '一个非常丰富和精心建造的结构，镶有精细的金属，如银。维持奢华的生活方式需要极高的费用。',
    'Assists you in completing day to day activities, giving you more time to be productive at work.': '帮助你完成每天的活动，给你更多的时间在工作中更有效率。',
    'Bend space and time through forbidden techniques, resulting in a faster gamespeed.': '通过禁止的技术扭曲空间和时间，导致更快的游戏速度。',
    'Blessed with unparalleled talent, perform unbelievable feats with magic at will. It is said that a master wizard has enough destructive power to wipe an empire off the map.': '拥有无与伦比的天赋，可以随心所欲地施展难以置信的魔术。据说大法师拥有足够的破坏力，足以将一个帝国从地图上抹去。',
    'More experienced and useful than the average footman, take out the enemy forces in battle with your might. The pay is not that bad.': '比普通步兵更有经验，更有用，在战斗中用你的力量消灭敌人。(工资没那么低。)',
    'Study the tricks of the trade and persuasive skills to lower any type of expense.': '学习交易技巧和说服技巧来降低任何类型的费用。',
    'Tame the raging and growing evil within you, improving evil gain in-between rebirths.': '驯服你内心的愤怒和增长的邪恶，在转世之间提高邪恶增益。',
    'This means you will learn everything again much more quickly than you did in your previous life.': '这意味着你会比上辈子更快地重新学习所有东西。',
    'Through harnessing ancient, forbidden techniques, lengthen your lifespan drastically beyond comprehension.': '通过利用古老的、被禁止的技术，将你的寿命大大延长到无法理解的程度。',
    'Through the means of dark magic, multiply the raw matter of the coins you receive from your job.': '通过黑魔法，将您从工作中获得的硬币的原始物质相乘。',
    'Travel from town to town, bartering fine goods. The job pays decently well and is a lot less manually-intensive.': '从一个城镇到另一个城镇，以物易物。这份工作报酬不错，而且不需要太多的体力劳动。',
    'Turn the tides of battle through casting intermediate spells and mentor other apprentices. The pay for this particular job is extremely high.': '通过施放中间法术和指导其他学徒来扭转战斗的趋势。这份工作的报酬非常高。',
    'Under the supervision of a mage, perform basic spells against enemies in battle. Generous pay will be provided to cover living costs.': '在法师的指导下，在战斗中对敌人施展基本法术。将提供相当数量的工资以支付生活费用。',
    'Utilise advanced spells to ravage and destroy entire legions of enemy soldiers. Only a small percentage of mages deserve to attain this role and are rewarded with an insanely high pay.': '使用先进的法术来蹂躏和摧毁整个军团的敌人士兵。只有一小部分的法师配得上这个角色，并能得到高得离谱的报酬。',
    'Utilising your unmatched combat ability, slaugher enemies effortlessly. Most footmen in the military would never be able to acquire such a well paying job like this.': '利用你无与伦比的战斗能力，毫不费力地屠杀敌人。军队里的大多数步兵都不可能得到这样一份报酬优厚的工作。',
    'Your age has met your lifespan, use the amulet to rebirth before you pass away': '你的年龄已经达到了你的寿命，用护身符在你死前重生',
    'Improve your learning speed through practising intense concentration activities.': '通过练习集中注意力的活动来提高你的学习速度。',
    'A dedicated area which provides many fine stationary and equipment designed for furthering your progress in research.': '一个专门的区域，提供了许多精致的文具和装备设计，以促进您的研究进展。',
    'A building formed from stone bricks and sturdy timber, which contains a few rooms. Although quite expensive, it is a comfortable abode.': '用石头、砖和坚固的木材建造的建筑，里面有几个房间。虽然很贵，但这是一个舒适的住所。',
    "Save to file": "保存到文件",
    "Scales Of Thought": "思想天平",
    "Secret": "秘密",
    "Senior": "高级",
    "Shabby logs and dirty hay glued together with horse manure. Much more sturdy than a tent, however, the stench isn't very pleasant.": "破旧的原木和肮脏的干草与马粪粘在一起。然而，比帐篷坚固得多，恶臭不是很令人愉快。",
    "Shop": "商店",
    "Skills": "技能",
    "Skip": "跳过",
    "Slash and pierce through enemy soldiers with ease, while covered in steel from head to toe. A decently paying and very respectable job.": "轻而易举地砍杀并刺穿敌方士兵，同时从头到脚全身覆盖着钢铁。一份体面的薪水和非常受人尊敬的工作。",
    "Sleep on the uncomfortable, filthy streets while almost freezing to death every night. It cannot get any worse than this.": "睡在不舒服、肮脏的街道上，每晚都几乎冻死。不能比这更糟了。",
    "Small Field": "小田地",
    "Small Manor": "小庄园",
    "Small palace": "小宫殿",
    "Small Shop": "小店",
    "Smelt ores and carefully forge weapons for the military. A respectable and OK paying commoner job.": "为军队冶炼矿石并精心打造武器。一份受人尊敬且报酬还可以的平民工作。",
    "Something tells you that the amulet might transform even further after living for": "有人告诉你，护身符可能会在生活后进一步转变",
    "Soon!": "很快！",
    "Sophomore": "大二",
    "Squire": "护卫",
    "Steel longsword": "钢长剑",
    "Stores a collection of books, each containing vast amounts of information from basic life skills to complex magic spells.": "存放着一系列书籍，每本书都包含从基本生活技能到复杂魔法的大量信息。",
    "Strength": "力量",
    "Strengthen your mana channels throughout your body, aiding you in becoming a more powerful magical user.": "加强你全身的法力通道，帮助你成为更强大的魔法使用者。",
    "Strengthen your neurons through habit and repetition, improving strength gains throughout the body.": "通过习惯和重复来增强你的神经元，提高整个身体的力量增益。",
    "Structured with a timber frame and a thatched roof. Provides decent living conditions for a fair price.": "结构为木框架和茅草屋顶。以合理的价格提供体面的生活条件。",
    "Struggle day and night for a couple of copper coins. It feels like you are at the brink of death each day.": "为几枚铜币日夜奋斗。感觉就像你每天都在死亡的边缘。",
    "Student": "学生",
    "Study desk": "书桌",
    "Study the theory of mana and practice basic spells. There is minor pay to cover living costs, however, this is a necessary stage in becoming a mage.": "学习法力理论并练习基本法术。支付生活费用的报酬很少，但是，这是成为法师的必要阶段。",
    "Study the tricks of the trade and persuasive skills to lower any type of expense.": "研究交易技巧和说服技巧以降低任何类型的费用。",
    "Super immortality": "超级不朽",
    "Tame the raging and growing evil within you, improving evil gain in-between rebirths.": "驯服你内心肆虐和增长的邪恶，提高重生之间的邪恶收益。",
    "Task": "任务",
    "Tent": "帐篷",
    "The Arcane Association": "奥术协会",
    "The finest $3 pizza modern food science can conceive": "现代食品科学能想到的最好的 3 美元比萨饼",
    "The nobility cares not for your tooltip desires.": "贵族不在乎你的工具提示欲望。",
    "The Order of Discovery": "发现秩序",
    "The potential routes of experimentation are infinite. The questions, limitless. What should a budding Chairman focus on in order to enhance their knowledge of both life and magic? In medieval times, biology is limited by the tools of the time. Without microscopes and advanced chemistry, it is almost impossible to fully grasp the concept of cellular life and the underlying mechanisms governing DNA, metabolism, and degradation of biological structures. Magical Engineering is a worthy pursuit for a Chairman looking to use Magic to build the tools of future scientific inquiry.": "潜在的实验路线是无限的。问题，无穷无尽。一个崭露头角的会长应该关注什么来增强他们对生命和魔法的了解？在中世纪，生物学受到当时工具的限制。没有显微镜和先进的化学，几乎不可能完全掌握细胞生命的概念以及控制 DNA、代谢和生物结构降解的潜在机制。对于希望使用魔法来构建未来科学探究工具的会长来说，魔法工程是一项值得追求的目标。",
    "This means you will learn everything again much more quickly than you did in your previous life.": "这意味着您将比前世更快地再次学习所有内容。",
    "This sweet chestnut horse will haul you and your trade goods to distant cities where your novel fabrics and knick knacks will fetch a tidy profit.": "这匹甜美的栗色马会将您和您的贸易货物拖到遥远的城市，在那里您的新颖面料和小摆设将获得可观的利润。",
    "Through harnessing ancient, forbidden techniques, lengthen your lifespan drastically beyond comprehension.": "通过利用古老的禁忌技术，大大延长你的寿命，超出你的理解。",
    "Through Magical Biology, a Chairman seeks to leverage their new inventions and new frames of thought to directly probe, change, experiment and observe the effects of magic on various cellular structures to enhance their vitality and vigor. Magical Biology is the final step towards immortality.": "通过魔法生物学，会长试图利用他们的新发明和新思维框架来直接探索、改变、实验和观察魔法对各种细胞结构的影响，以增强他们的活力和活力。神奇生物学是迈向永生的最后一步。",
    "Through the means of dark magic, multiply the raw matter of the coins you receive from your job.": "通过黑魔法的手段，倍增你从工作中获得的硬币的原材料。",
    "Time warping": "时间扭曲",
    "Toggle": "切换",
    "Toggle light/dark mode": "切换亮/暗模式",
    "Touch the eye": "触摸眼球",
    "Town": "小镇",
    "Town Income per day": "城镇每天收入",
    "Trade Psychology": "贸易心理学",
    "Travel from town to town, bartering fine goods. The job pays decently well and is a lot less manually-intensive.": "从一个城镇到另一个城镇旅行，以物易物。这项工作的薪水不错，而且人工密集程度要低得多。",
    "Try as I do, these temporary tooltips are poo.": "像我一样尝试，这些临时工具提示很糟糕。",
    "Turn the tides of battle through casting intermediate spells and mentor other apprentices. The pay for this particular job is extremely high.": "通过施展中级法术和指导其他学徒扭转战局。这项特殊工作的薪水非常高。",
    "Under the supervision of a mage, perform basic spells against enemies in battle. Generous pay will be provided to cover living costs.": "在法师的监督下，对战斗中的敌人施展基本法术。将提供丰厚的报酬以支付生活费用。",
    "Unusual Insight": "非凡洞察力",
    "Up to this point, a Chairman's experience with Magic is almost entirely on the human scale. A budding apprentice learns to extend the life of a flower. A mage learns to incinerate man, horse, and siege engine. Master Wizards learn to shake the earth and obscure the vision of their human opponents with natural phenomena and magic alike. A Chairman must learn to shift their focus from the scale of humanity to both higher highs and lower lows. A Chairman seeking immortality must investigate the smallest structures of existence, must continue probing deeper and uncovering astounding knowledge and even more astounding questions. Scales of Thought will enhance Mana Control and Chairman experience gain rates by a substantial rate. By probing nature on a deeper level, a Chairman gains unparalleled understanding which influences every magical action pursuit.": "到目前为止，会长对万智牌的体验几乎完全是在人的范围内。一个初出茅庐的学徒学习延长一朵花的寿命。法师学会焚烧人、马和攻城车。大法师学会用自然现象和魔法来震动地球并模糊他们人类对手的视野。会长必须学会将他们的注意力从人性的尺度转移到更高的高度和更低的低点。一个追求长生不老的会长，必须研究最小的存在结构，必须继续深入探索，发现惊人的知识，甚至更惊人的问题。思想规模将显着提高法力控制和会长经验获取率。通过在更深层次上探索自然，会长获得了无与伦比的理解力，这种理解力影响着每一个神奇的行动追求。",
    "Utilise advanced spells to ravage and destroy entire legions of enemy soldiers. Only a small percentage of mages deserve to attain this role and are rewarded with an insanely high pay.": "利用先进的法术蹂躏和摧毁敌方士兵的整个军团。只有一小部分法师配得上这个角色，并获得高得离谱的报酬。",
    "Utilising your unmatched combat ability, slaugher enemies effortlessly. Most footmen in the military would never be able to acquire such a well paying job like this.": "利用你无与伦比的战斗能力，毫不费力地屠杀敌人。军队中的大多数步兵永远无法获得如此高薪的工作。",
    "Veteran footman": "资深步兵",
    "Veteran knight": "资深骑士",
    "Vice Count": "侯爵",
    "Weapon Outlet": "武器出口",
    "With your newfound land and tools, you've become relatively wealthy. For a peasant farmer, at least. Tale of your achievements has reached the ears of the local lord, who has granted permission for you to rent one of his oxen plow teams and associated gear.": "有了新发现的土地和工具，你变得相对富有。至少对于农民来说。你的成就传到了当地领主的耳中，他允许你租用他的一个牛犁队和相关装备。",
    "Witty placeholder, my name is.": "机智的占位符，我的名字是。",
    "Wizard": "巫师",
    "Wooden hut": "木屋",
    "Wooden Hut": "木屋",
    "Writers pour their souls into the written word. Your extensive reading combined with your countless years spent interacting with people have lent you unparalleled insight into the way mankind views the positive and the negative events of this world. An ethical scholar would refrain from abusing this knowledge for financial gain.": "作家将他们的灵魂倾注在文字中。您的广泛阅读加上您与人交往的无数年，让您对人类看待这个世界的积极和消极事件的方式有了无与伦比的洞察力。伦理学者会避免滥用这些知识谋取经济利益。",
    "Xp left": "经验剩余",
    "xp multipliers": "经验乘数",
    "Xp/day": "经验/天",
    "years": "年",
    "You found this cracked fishing rod partially buried by the shore. It needs some major TLC, but it'll help you reel in bigger fish.": "你发现这根破裂的钓鱼竿部分被岸边掩埋。它需要一些主要的 TLC，但它会帮助你钓到更大的鱼。",
    "You stumble across a strange looking amulet on your 25th birthday. It does not look like\n                            it has any worth on the market given that it's made from cheap-looking copper. However, you\n                            feel a weird urge to keep the amulet, so you slip it into your pocket for safekeeping.": "你在 25 岁生日时偶然发现了一个看起来很奇怪的护身符。它看起来不像\n 它在市场上没有任何价值，因为它是由看起来很便宜的铜制成的。但是，您\n 有一种保留护身符的奇怪冲动，因此您将其放入口袋以妥善保管。",
    "You're pretty sure this lumpy hunk of iron used to be someone's chamber pot.": "你很确定这块块状的铁块曾经是某人的夜壶。",
    "Your age has met your lifespan, use the amulet to rebirth before you pass away": "你的年龄已经到了你的寿命，在你去世之前使用护身符重生",
    "Your first shop. This cozy storefront lies on the main street of a medium-sized walled town. Commoners, nobles, and military patrols all pass along this street, so at the very least people will know your store exists.": "你的第一家店。这家舒适的店面位于一个中型围城的主要街道上。平民、贵族和军事巡逻队都在这条街上经过，所以至少人们会知道你的商店存在。",
    "Your gut instinct was right. The moment you hit the grand age of 200, you hear an ominous hum coming from the amulet.\n                                A mouth emerges from its surface and begins to cackle, and proceeds to say: \"So you've made it this far... Are you ready to embrace evil?\"": "你的直觉是对的，当你真的达到200岁高龄时，护身符发出了不祥的嗡嗡声。一张嘴从它的表面露出，它咯咯笑着说道“所以你已经走到了这一步。准备好拥抱邪恶了吗？”",
    "Your heroic feats in battle have earned you a title of nobility and a huge swath of some rather...undesirable land. \n                        Your territory is hundreds of miles from the nearest village, the soil is infertile, and the few living beings around are bandits and hermits. It's going to \n                        take a lot of work to make this place worth anything.": "你在战斗中的英勇壮举为你赢得了贵族头衔和一大片相当……不受欢迎的土地。 \n 你的领地距离最近的村庄数百里，土质贫瘠，周围为数不多的生灵是土匪和隐士。 \n 要让这个地方物有所值，需要做很多工作。",
    "Your leadership of the caretaking team has proven you have a modicum of brain cells. A teacher you frequently see has vouched for your potential. Your studies are long and often boring, but you can sense there are great secrets within these halls waiting to be discovered.": "你对看护团队的领导已经证明你有少量的脑细胞。你经常见到的一位老师已经证明了你的潜力。你的学习时间很长，而且常常很无聊，但你能感觉到这些大厅里有很多秘密等待被发现。",
    "Your people won't become spoiled while living in huts such as these; they'll be one with nature.": "住在这样的小屋里，你的人民不会被宠坏；他们将与自然合而为一。",
    "Your rising status has granted you access to a small countryside manor. With the manor comes two hundred acres of farmland and the associated serfs, grain mill, and a small river for irrigation. The attendant tells you of a beautiful hollow in some nearby woods where you can relax and meditate.": "您不断上升的地位使您可以进入一个小乡村庄园。庄园里有两百英亩的农田和相关的农奴、磨坊和一条用于灌溉的小河。服务员告诉您在附近的一些树林里有一个美丽的空洞，您可以在那里放松和冥想。",
    "Your training in the more mundane affairs of the non-magical world have developed your critical analysis skills. As you gain knowledge, magical concepts which seemed inscrutable and mysterious are becoming more relatable to the physical world around you.": "你在非魔法世界更平凡事务中的训练培养了你的批判性分析技能。随着你获得知识，那些看似神秘莫测的魔法概念正变得与你周围的物理世界更加相关。",
    "Fill your mind with peace and tranquility to tap into greater happiness from within.": "让你的心灵充满平静与安宁，从内心获得更大的幸福。",
    "Fisherman": "渔夫",
    "Flow": "流动",
    "Footman": "步兵",
    "for your jobs and skills equivalent to": "你的工作和技能相当于",
    "Forget me not, for this author shall not.": "不要忘记我，因为这位作者不会。",
    "Freshman": "新生",
    "Fundamentals": "基本原理",
    "Go outside.": "出去。",
    "Good.": "好的。",
    "Grain Shed": "粮棚",
    "Grand Duke": "大公",
    "Grand palace": "大宫殿",
    "Grow and culture the evil within you through the sacrifise of other living beings, drastically increasing evil gain.": "通过牺牲其他众生来培养和培养你内心的邪恶，大大增加邪恶的收益。",
    "Happiness": "幸福",
    "Hard reset game": "硬重置游戏",
    "Having completed your basic studies, the Order grants you a bottom-of-the-barrel position as research associate to an old member of little renown. Any major misstep will probably result in your banishment from the halls of knowledge.": "完成基础学习后，骑士团授予您一个底层职位，担任一位名不见经传的老成员的研究助理。任何重大失误都可能导致你被逐出知识殿堂。",
    "Healing the soil is a monumental undertaking. It will doubtless take generations of care. Or some nifty magic...": "修复土壤是一项艰巨的任务。毫无疑问，它需要几代人的照顾。或者一些漂亮的魔法......",
    "Heavy tools used in strenuous exercise to toughen up and accumulate strength even faster than before.": "用于剧烈运动的重型工具比以前更快地增强和积累力量。",
    "High King": "至高王",
    "High Lord": "大领主",
    "Holy knight": "圣骑士",
    "Homeless": "无家可归",
    "House": "房子",
    "Idle citizens: 0": "闲散市民：0",
    "If you decide to embrace evil, there is a price. All of your levels, coins and even max levels will be reset.\n                                Your town will be utterly annihilated; your townspeople slaughtered by your own hand.\n                                You will be reborn as a fresh slate. However, you will unlock a new line of skills and gain": "如果你决定拥抱邪恶，那是有代价的。你所有的等级、金币甚至最高等级都将被重置。\n你的城镇将被彻底歼灭；你的镇民被你亲手屠杀。\n你将重生为新的石板。但是，您将解锁新的技能线并获得",
    "Illustrious Chairman": "杰出的会长",
    "Immortality": "不朽",
    "Import/export save": "导入/导出保存",
    "Improve your learning speed through practising intense concentration activities.": "通过练习集中注意力的活动来提高您的学习速度。",
    "Income/day": "收入/天",
    "Intense bouts of concentration warp your perception of time": "强烈的注意力会扭曲你对时间的感知",
    "Intimidation": "恐吓",
    "Is it April 20th?": "是4月20日吗？",
    "It's poo.": "是便便。",
    "Jobs": "工作",
    "Join the discord community!": "加入discord社区！",
    "Junior": "初级",
    "Junior Caretaker": "初级看守",
    "Keeps your household clean at all times and also prepares three delicious meals per day, leaving you in a happier, stress-free mood.": "让您的家庭时刻保持清洁，每天还准备三顿可口的饭菜，让您拥有更幸福、无压力的心情。",
    "King": "国王",
    "Knight": "骑士",
    "Large house": "大房子",
    "Lead Caretaker": "看守主管",
    "Learn to emit a devilish aura which strikes extreme fear into other merchants, forcing them to give you heavy discounts.": "学会散发出令其他商人极度恐惧的恶魔气息，迫使他们给你大量折扣。",
    "Learn to procrastinate less at work and receive more job experience per day.": "学会在工作中减少拖延，每天获得更多的工作经验。",
    "Legendary knight": "传奇骑士",
    "Lengthen your lifespan through the means of magic. However, is this truly the immortality you have tried seeking for...?": "通过魔法延长你的寿命。然而，这真的是你努力寻求的不朽吗……？",
    "Level": "等级",
    "Library": "图书馆",
    "Lifespan": "寿命",
    "Livestock-derived Fertilizer": "畜禽肥料",
    "Load from file": "从文件加载",
    "Lord": "领主",
    "Mage": "法师",
    "Magic": "魔法",
    "Magical Biology": "神奇生物学",
    "Magical Engineering": "魔法工程",
    "Mana control": "法力控制",
    "Master of life and war. Renowned throughout the magical and non-magical worlds alike, an Illustrious Chairman is completely free to follow their own path of discovery and ambition. On the other hand, there is that curious note to investigate...": "生活与战争的大师。赫赫有名的会长在魔法和非魔法世界都享有盛誉，他完全可以自由地追随自己的探索和野心之路。另一方面，有一个奇怪的笔记需要调查......",
    "Master wizard": "大法师",
    "Max level": "最高等级",
    "Meditation": "冥想",
    "Merchant": "商人",
    "Military": "军队",
    "Mind": "思想",
    "Miner": "矿工",
    "Miner's Lantern": "矿工灯笼",
    "Misc": "杂项",
    "More experienced and useful than the average footman, take out the enemy forces in battle with your might. The pay is not that bad.": "比普通步兵更有经验和有用，在战斗中用你的力量消灭敌军。工资没那么差。",
    "Much larger than a regular house, which boasts even more rooms and multiple floors. The building is quite spacious but comes with a hefty price tag.": "比拥有更多房间和多层楼的普通房子大得多。该建筑非常宽敞，但价格却很高。",
    "Muscle memory": "肌肉记忆",
    "Net/day": "净/天",
    "Nobility": "贵族",
    "Note: Your town's abuse of the grain markets has been noted. Expect the kingdon to limit your egregious profits soon.": "注意：您所在城镇滥用粮食市场的行为已被注意到。期待国王很快限制你的巨额利润。",
    "Novel Knowledge": "新知识",
    "Now to find yourself a nice Queen. Or two. Or three.": "现在给自己找一个漂亮的女王。或者两个。或三个。",
    "Obliterate squadrons of enemy soldiers in one go with extraordinary proficiency, while equipped with the finest gear. Such a feared unit on the battlefield is paid extremely well.": "以非凡的熟练度一口气消灭敌方士兵的中队，同时配备最好的装备。战场上这样一个令人恐惧的单位，薪水非常好。",
    "Oh lord, please let Gottmilk write the real tooltips already. These are too painful to endure.": "哦，上帝，请让 Gottmilk 写出真正的工具提示。这些太痛苦了，无法忍受。",
    "On your 45th birthday, you feel the amulet shiver uncontrollably in your pocket. You take it\n                            out and the constant shivering suddenly stops. More to your bizarre surprise, you notice\n                            a strange etching on the centre of the amulet.": "在您 45 岁生日时，您会感到口袋里的护身符不受控制地颤抖。你把它拿出来，不断的颤抖突然停止了。更令您惊讶的是，您注意到护身符中心有一个奇怪的蚀刻。",
    "On your 65th birthday, you once again encounter the strange, unexplained shivering from your\n                                amulet. But this time, a living eyeball emerges from the centre. Although terribly frightened,\n                                you realise you do not have many years to live left anyway so you consider touching the eye\n                                to see what happens.": "在你65岁生日那天，护身符再次发出奇怪的、无法解释的颤动。而且，一个活生生的眼球从护身符的中心冒了出来！尽管你非常害怕，但你意识到你已时日无多，所以你尝试触摸这个眼球，看看会发生什么。",
    "Ox-driven Plow": "牛驱犁",
    "Pack Horse": "驮马",
    "Pause": "暂停",
    "Personal squire": "个人侍从",
    "Plow the fields and grow the crops. It's not much but it's honest work.": "耕种田地，种植庄稼。这不是很多，但它是诚实的工作。",
    "Probation": "实习生",
    "Productivity": "效率",
    "Progress Knight - Reborn": "骑士进度条：重生",
    "Projects": "项目",
    "Properties": "特性",
    "Put down your life to battle with enemy soldiers. A courageous, respectable job but you are still worthless in the grand scheme of things.": "放下你的生命与敌方士兵战斗。一份勇敢、受人尊敬的工作，但在宏伟的计划中你仍然一文不值。",
    "Rag Clothing": "破布衣服",
    "Reel in various fish and sell them for a handful of coins. A relaxing but still a poor paying job.": "卷入各种鱼并以少量硬币出售。一份轻松但收入仍然很低的工作。",
    "Required: ": "要求：",
    "Research": "研究",
    "Reset": "重置",
    "Rhyming is crime-ing, and feature delay is not the way.": "押韵是犯罪，功能延迟不是办法。",
    "Rocks abound within these sour patches of inhospitable soil you and your people call \"farms\".": "在你和你的人民称之为“农场”的这些荒凉的土壤中，岩石比比皆是。",
    "Sapphire charm": "蓝宝石吊饰",
    ", which will heavily impact your future lives.": "，这将严重影响你未来的生活。",
    "1 + the max level of the skill or job / 10.": "1 + 技能或工作的最高等级 / 10。",
    "2 whole centuries": "2 整个世纪",
    "A building formed from stone bricks and sturdy timber, which contains a few rooms. Although quite expensive, it is a comfortable abode.": "由石砖和坚固的木材组成的建筑物，其中包含几个房间。虽然很贵，但是住的很舒服。",
    "A busy military means a busy weapons store. One of the liuetenants who frequents your small shop recently let slip that a long military campaign is imminent. Naturally, a savy merchant such as yourself sees the business opportunity provided by war.": "忙碌的军队意味着忙碌的武器商店。最近经常光顾您的小商店的一位中尉透露，一场漫长的军事行动迫在眉睫。像您这样精明的商人自然会看到战争带来的商机。",
    "A dedicated area which provides many fine stationary and equipment designed for furthering your progress in research.": "一个专门的区域，提供许多精美的文具和设备，旨在促进您的研究进展。",
    "A fine blade used to slay enemies even quicker in combat and therefore gain more experience.": "用于在战斗中更快地杀死敌人并因此获得更多经验的精美刀片。",
    "A grand residence completely composed of gold and silver. Provides the utmost luxurious and comfortable living conditions possible for a ludicrous price.": "一座完全由金银组成的宏伟住宅。以可笑的价格提供最豪华和舒适的生活条件。",
    "A humble dwelling that provides the basic requirements of nature. \n                            Rough wooden logs join together in support of brown thatched roofing, providing a cozy retreat from rain and wind.": "提供自然基本要求的简陋住宅。 \n 粗糙的原木连接在一起，支撑着棕色的茅草屋顶，提供了一个舒适的避风港避风港。",
    "A low-level administrator of the ancient Order of Discovery has offered you a job. Cleaning shit-stained chamber pots and mopping kitchen floors isn't glamorous work, but it gives you the rare chance to peruse the Order's world-class library of exotic books. Who cares if touching the books is an offense worthy of expulsion?": "古代发现勋章的一位低级管理员为您提供了一份工作。清洁脏兮兮的夜壶和拖地厨房地板并不是一件光鲜亮丽的工作，但它让您有难得的机会细读骑士团世界级的异国书籍图书馆。谁在乎触摸书籍是否是值得开除的罪行？",
    "A mere human body is too feeble and weak to withstand evil. Train with forbidden methods to slowly manifest into a demon, capable of absorbing knowledge rapidly.": "单纯的人体实在是太虚弱无力，无法抵挡邪恶。修炼禁法，慢慢化身为魔，快速吸收知识。",
    "A mind needs training. Your time spent absorbing new ideas and worldviews has increased your ability to assimilate new ideas and make connections between seemingly unrelated concepts.": "头脑需要训练。你花在吸收新想法和世界观上的时间提高了你吸收新想法和在看似不相关的概念之间建立联系的能力。",
    "A place to write down all your thoughts and discoveries, allowing you to learn a lot more quickly.": "一个写下你所有想法和发现的地方，让你学得更快。",
    "A savy merchant knows the dynamics of supply and demand. Besides the obvious fact that storing your grain delays that pesky nuisance of winter starvation,\n                            your grain sheds allow your townsfolk to hold off selling their grain until prices rise. The more grain storage your town builds, the more influence on prices\n                            your town wields.": "精明的商人了解供需动态。除了储存谷物可以延缓令人讨厌的冬季饥饿问题这一显而易见的事实之外，\n 您的谷物棚让您的城镇居民可以推迟出售谷物，直到价格上涨。您的城镇建立的粮食储存越多，对您城镇的价格的影响就越大。",
    "A set of rusty iron tools to help loosen soil, shape wood, and attach things. Where did you even find this junk?": "一套生锈的铁工具，用于帮助松土、塑造木头和连接东西。你在哪里找到这个垃圾？",
    "A thin sheet of tattered cloth held up by a couple of feeble, wooden sticks. Horrible living conditions but at least you have a roof over your head.": "几根软弱的木棍支撑着一块破布。糟糕的生活条件，但至少你有一个屋顶。",
    "A tooltip, a thought. Helpful, I am not.": "一个工具提示，一个想法。有帮助，我没有。",
    "A very rich and meticulously built structure rimmed with fine metals such as silver. Extremely high expenses to maintain for a lavish lifestyle.": "一个非常丰富且精心打造的结构，边缘镶有银等精美金属。维持奢侈生活方式的费用极高。",
    "Active": "激活",
    "Affects all xp gain": "影响所有经验增益",
    "Affects dark magic xp gain": "影响黑魔法的经验值增益",
    "Affects game speed": "影响游戏速度",
    "After a pitched battle between bickering barons, your fellow farmer lost his leg and two eldest sons. With a wife and small children to take care of, he says he'll entrust his land to you in exchange for using the proceeds to take care of his family.": "在争吵不休的贵族之间展开激战后，你的农民同伴失去了一条腿和两个长子。有妻子和小孩要照顾，他说他会把他的土地交给你，以换取用收益来照顾他的家人。",
    "After weeks of feeling your way through pitch black tunnels, bandaging scraped hands, and getting smacked in the face by your fellow miner's pickaxes, you have the bright idea to purchase a lantern. Hopefully some light will help illuminate additional mineral deposits and geological phenomena.": "经过数周的摸索穿过漆黑的隧道，包扎擦伤的手，并被你的矿工的镐打在脸上，你有了购买灯笼的好主意。希望一些光线将有助于照亮更多的矿藏和地质现象。",
    "After weeks of freezing on the streets, you're making enough money to buy some cheap clothes. They're not much, but they'll keep you warm enough to focus.": "在街上冻了几个星期之后，你赚到了足够的钱买一些便宜的衣服。它们并不多，但它们会让你保持足够的温暖以集中注意力。",
    "Age": "年龄",
    "Age has caught up to you": "年龄已经赶上了你",
    "Amulet": "护身符",
    "Apprentice mage": "魔法学徒",
    "Arch Duke": "大公爵",
    "Are these placeholder tooltips infuriating?": "这些占位符工具提示是否令人愤怒？",
    "As you walk amongst your fellow Master Wizards, who in recognition of your vast power have just elected you Chairman of the Arcane Association, you receive this anonymous note: \"We have followed your progress with great interest. Many have walked this path, but few have used the amulet you now wear to its full potential. But you are not the first to make it this far. Strive on. We will contact you, when the time is right.\"": "当你走在你的大法师们中间，他们对你巨大的力量的认可刚刚选举你为奥术协会会长，你会收到这样一封匿名信：“我们怀着极大的兴趣关注着你的进步。很多人都走过这条路，但很少有人将你现在佩戴的护身符发挥其全部潜力。但你并不是第一个做到这一点的人。继续努力。我们会在适当的时候与你联系。\"",
    "Assists you in completing day to day activities, giving you more time to be productive at work.": "帮助您完成日常活动，让您有更多时间在工作中高效工作。",
    "Auto-learn": "自动学习",
    "Auto-promote": "自动提升",
    "Balance (in coins": "余额（硬币",
    "Bargaining": "讨价还价",
    "Baron": "男爵",
    "Baronet": "准男爵",
    "Basic Buildings": "基本建筑",
    "Basic Farm Tools": "基本农具",
    "Battle tactics": "战斗战术",
    "Because Viscount sounds gross.": "因为子爵听起来很恶心。",
    "Beggar": "乞丐",
    "Bend space and time through forbidden techniques, resulting in a faster gamespeed.": "通过禁忌技巧弯曲空间和时间，从而加快游戏速度。",
    "Blacksmith": "铁匠",
    "Blessed with unparalleled talent, perform unbelievable feats with magic at will. It is said that a master wizard has enough destructive power to wipe an empire off the map.": "拥有无与伦比的天赋，随心所欲地用魔法完成令人难以置信的壮举。据说大法师的破坏力足以将一个帝国从地图上抹去。",
    "Book": "书",
    "Breech Bellows": "后膛波纹管",
    "Build": "建造",
    "Butler": "男管家",
    "By touching the eyeball, you will be reborn and have to restart life again, losing all your levels and coins.\n                                However, you will gain": "触摸眼球，你将重生，必须重新开始生活，失去所有等级和硬币。\n但是，你会获得",
    "Carry around your knight's shield and sword along the battlefield. Very meager pay but the work experience is quite valuable.": "在战场上随身携带骑士的盾牌和剑。工资很低，但工作经验很有价值。",
    "Chairman": "会长",
    "Cheap Fishing Rod": "便宜的钓鱼竿",
    "Cobbled together with two sticks and a pair of old trousers, this tool boosts the heat and efficiency of your forge.": "用两根木棍和一条旧裤子拼凑而成，这个工具可以提高锻造的热量和效率。",
    "Collapse entire armies in mere seconds with your magically imbued blade. The handful of elite knights who attain this level of power are showered with coins.": "用你的魔法剑在几秒钟内瓦解整个军队。少数获得这种力量的精英骑士会得到大量硬币。",
    "Combat": "战斗",
    "Common work": "普通工作",
    "Concentration": "专注",
    "Condition your body and strength through harsh training. Stronger individuals are paid more in the military.": "通过严格的训练来调节你的身体和力量。更强壮的人在军队中的报酬更高。",
    "Cottage": "茅屋",
    "Count": "伯爵",
    "Crappy Anvil": "蹩脚的铁砧",
    "Create and revise battle strategies, improving experience gained in the military.": "创建和修改战斗战术，提高在军队中获得的经验。",
    "Current job": "当前工作",
    "Current skill": "当前技能",
    "Dark influence": "黑暗的影响",
    "Dark magic": "黑暗魔法",
    "Day": "\t\t天数\t",
    "Delve into dangerous caverns and mine valuable ores. The pay is quite meager compared to the risk involved.": "深入危险的洞穴并开采有价值的矿石。与所涉及的风险相比，报酬相当微薄。",
    "Demon training": "恶魔训练",
    "Demon's wealth": "恶魔的财富",
    "Duke": "公爵",
    "Dumbbells": "哑铃",
    "Effect: Additional 6% Farm income (compounding)": "效果：额外 6% 的农场收入（复合）",
    "Effect: Additional daily income: 150 coppers": "效果：每日额外收入：150铜币",
    "Effect: None": "效果：无",
    "Elite knight": "精英骑士",
    "Embedded with a rare sapphire, this charm activates more mana channels within your body, providing a much easier time learning magic.": "这款护身符嵌入了稀有蓝宝石，可激活体内更多的法力通道，让学习魔法更加轻松。",
    "Embrace evil": "拥抱邪恶",
    "Emperor of Mankind": "人类皇帝",
    "Enable warp": "启用扭曲",
    "Encompass yourself with formidable power bestowed upon you by evil, allowing you to pick up and absorb any job or skill with ease.": "用邪恶赋予你的强大力量包围自己，让你轻松掌握和吸收任何工作或技能。",
    "Even grander than the most grand Grand Duke your granddad could....Grand.": "甚至比你祖父所能做到的最伟大的大公还要伟大……伟大。",
    "Even higher. Even nobler.": "更高。 甚至更高贵。",
    "evil": "邪恶",
    "Evil": "邪恶",
    "Evil control": "邪恶控制",
    "Expense/day": "费用/天",
    "Farm": "农场",
    "Farmer": "农民",
    "Feared worldwide, obliterate entire nations in a blink of an eye. Roughly every century, only one holy knight is worthy of receiving such an esteemed title.": "举世畏惧，眨眼间灭尽万国。 几乎每个世纪，只有一位圣骑士配得上如此尊贵的称号。",
    "Cost": "成本",
    "Idle citizens": "空闲市民",
    "Effect: Additional 6% Farm income (compounding": "效果:增加6%的农场收入(复利",
    "Novel Knowledge lvl": "新知识等级",
    "Lord lvl": "领主等级",
    "Unusual Insight lvl": "非凡洞察力等级",
    "Arch Duke lvl": "大公爵等级",
    "Blood meditation lvl": "血之冥想",
    "Demon's wealth lvl": "恶魔的财富",
    "Sophomore lvl": "公爵等级",
    "Duke lvl": "公爵等级",
    "Vice Count lvl": "侯爵等级",
    "Trade Psychology lvl": "贸易心理学等级",
    "Essence": "精华",
    "Essence collector": "精华收集器",
    "Essence Collector": "精华收集器",
    "Eternal Time": "永恒时间",
    "per day": "每天",
    "Progress Knight Quest": "骑士进度条2 Mod",
    "Real Time:": "真实时间：",
    "Rebirth": "重生",
    "reset": "重置",
    "Hero": "英雄",
    "Stats": "统计",
    "Strange Magic": "奇怪的魔法",
    "Superb Heroes": "超级英雄",
    "The new gold": "新的黄金",
    "Time Loop": "时间循环",
    "Time Warping": "时间扭曲",
    "Time Warping:": "时间扭曲：",
    "Upgrade": "升级",
    "Enter challenge": "进入挑战",
    "Engineering": "工程",
    "Essence:": "精华：",
    "Evil Control": "邪恶控制",
    "Evil gain": "邪恶增益",
    "Evil Gain": "邪恶增益",
    "Evil:": "邪恶：",
    "Export save": "导出存档",
    "Extended": "扩展",
    "Goal": "目标",
    "God bless you!": "上帝保佑你！",
    "Good Heroes": "英雄好汉",
    "Hell Portal": "地狱传送门",
    "Import save": "导入存档",
    "Holy Knight": "圣骑士",
    "Income": "收入",
    "Income:": "收入：",
    "Keep": "保持",
    "Keep pressing to change more": "保持长按改变更多",
    "Layout": "布局",
    "Original game:": "原始游戏：",
    "Reach": "达到",
    "Reach x": "达到 x",
    "A thousand years have come and gone and yet, you still remain alive... somehow. You feel your amulet shivering again and to your surprise, you see small tendrils\n\t\t\t\t\t\t\t\t\t\t\tfull of eyeballs emergin from it. As you are about to drop the amulet, you hear frightening screech followed by whispers in your head...": "一千年过去了，然而，你还活着……不知何故。 你感到你的护身符再次颤抖，令你惊讶的是，你看到细小的卷须\n\t\t\t\t\t\t\t\t\t\t\t上面长满了眼球。 当你正要放下护身符时，你听到可怕的尖叫声，接着是你脑海中的低语……",
    "A construct with the mass of Jupiter and a surface area millions of times that of Earth, capable of housing trillions of humans and other animals including alien species. The expenses are literally astronomical due to the maintenance involved in keeping the structure stable and the inside area habitable, but the massive living space is worth it.": "一个质量与木星相当、表面积是地球数百万倍的建筑，能够容纳数万亿人类和其他动物，包括外来物种。 由于涉及保持结构稳定和内部区域可居住的维护，费用简直是天文数字，但巨大的生活空间是值得的。",
    "OR": "或",
    "Ten millenia have passed... most of them spent serving the Void, yet there is still a glimpse of humanity inside of you. All of the sudden your amulet starts to glow in the distance,\n\t\t\t\t\t\t\t\t\t\t\tilluminating darkness around you with the brightness of a thousand suns. With the very last remnant of your free will, you run to your amulet and touch it...": "一万年过去了……他们中的大多数人都在为虚空服务，但在你的内心仍有人性的一瞥。 突然间，你的护身符开始在远处发光，\n\t\t\t\t\t\t\t\t\t\t\用一千个太阳的亮度照亮你周围的黑暗。 带着你最后一点自由意志，你跑到你的护身符前触摸它……",
    "will be reset. You will be reborn as a fresh slate in a new universe, with no memory of milestones and challenges from any of your past selves. In exchange, you will unlock a third new line of abilities and gain": "将被重置。 你将重生为新宇宙中的新人，没有任何你过去的里程碑和挑战的记忆。 作为交换，您将解锁第三条新的能力线并获得",
    "Xp left": "经验剩余",
    "XP gain by x": "经验增益 x",
    "You gain": "你获得",
    "You rule your very own galaxy the size of the Milky Way, with billions of planets organized into thousands of different states all under your control. While your power is astronomical, so are your responsibilities.": "你统治着你自己的银河系大小的星系，数十亿颗行星组织成数千种不同的状态，都在你的控制之下。 虽然你的力量是天文数字，但你的责任也是如此。",
    "You stumble across a strange looking amulet on your 25th birthday. It does not look like\n\t\t\t\t\t\t\t\t\t\tit has any worth on the market given that it's made from cheap-looking copper. However, you\n\t\t\t\t\t\t\t\t\t\tfeel a weird urge to keep the amulet, so you slip it into your pocket for safekeeping.\n\t\t\t\t\t\t\t\t\t": "在您 25 岁生日那天，您偶然发现了一个看起来很奇怪的护身符。 它看起来不像\n\t\t\t\t\t\t\t\t\t\t它在市场上有任何价值，因为它是由看起来很便宜的铜制成的。 然而，你\n\t\t\t\t\t\t\t\t\t\t有一种想保留护身符的奇怪冲动，所以你把它塞进口袋里妥善保管。\n\t\t\ t\t\t\t\t\t\t",
    "Your gut instinct was right. The moment you hit the grand age of 200, you hear an ominous hum coming from the amulet.\n\t\t\t\t\t\t\t\t\t\t\tA mouth emerges from its surface and begins to cackle, and proceeds to say: \"So you've made it this far... Are you ready to embrace evil?\"\n\t\t\t\t\t\t\t\t\t\t\t": "",
    "Ringworld": "环世界",
    "W I D E": "宽屏",
    "On your 45th birthday, you feel the amulet shiver uncontrollably in your pocket. You take it\n\t\t\t\t\t\t\t\t\t\tout and the constant shivering suddenly stops. More to your bizarre surprise, you notice\n\t\t\t\t\t\t\t\t\t\ta strange etching on the centre of the amulet.\n\t\t\t\t\t\t\t\t\t": "在您 45 岁生日那天，您感觉护身符在口袋里不受控制地颤抖。 你出了\n\t\t\t\t\t\t\t\t\t\t它，持续的颤抖突然停止了。 更让你感到奇怪的是，你注意到\n\t\t\t\t\t\t\t\t\t\护身符中心有奇怪的蚀刻。\n\t\t\t\t\ t\t\t\t\t",
    "Lifespan:": "寿命：",
    "but divide": "但除",
    ", all of your levels, coins, max levels, evil, and": "，你所有的等级，硬币，最高等级，邪恶，和",
    ", you will be reborn once again, losing all your coins,": "，你将再次重生，失去所有的硬币，",
    "\"Celestial Powers\"": "\"天上的力量\"",
    "\"Galactic Council\"": "“银河议会”",
    "\"The Void\"": "\“虚空\”",
    "\"Void Manipulation\"": "《虚空操纵》",
    "\"You are now part of something bigger than yourself...\"\n\t\t\t\t\t\t\t\t\t\t\t": "\"你现在是比你自己更大的事物的一部分......\"\n\t\t\t\t\t\t\t\t\t\t\t",
    "\"You have to embrace the Void...\"": "“你必须拥抱虚空……”",
    "(real time).": "（即时的）。",
    "⚠️ Oh no! It looks like something on the site broke.. If this issue persists, feel free to contact the developers.": "⚠️哦不！ 看起来网站上的某些东西坏了。如果此问题仍然存在，请随时与开发人员联系。",
    "1 + the max level of the class or ability / 10.": "所获得经验变为（1+最高等级/10）倍。",
    "1. An unhappy life": "1. 不幸的生活",
    "2. The rich and the poor": "2. 富人与穷人",
    "3. Time does not fly": "3.时间不会飞",
    "4. Dance with the devil": "4.与魔鬼共舞",
    "5. Legends never die": "5. 传奇永不消逝",
    "A cluster of galactic groups spanning hundreds of millions of light years across and containing thousands of galaxies is under your control.": "一个跨越数亿光年并包含数千个星系的星系团在你的控制之下。",
    "A Dark Era": "黑暗时代",
    "A deal with the Chairman": "与会长的交易",
    "A Dimension just for you that can be summoned at will. What happens there stays there.": "一个可以随意召唤的专属于你的次元。 那里发生的事情留在那里。",
    "A fully colonized network of stars and star systems spanning dozens of light years is ready for you to explore and call home.": "一个跨越数十光年的完全殖民的恒星和恒星系统网络已准备好供您探索和打电话回家。",
    "A gift from god": "上帝的礼物",
    "A miracle": "奇迹",
    "A new beginning": "一个新的开始",
    "A nigh-omnipotent cosmological entity, with vast matter and energy manipulation abilities that help you push the boundaries of the Universe itself.": "一个几乎无所不能的宇宙实体，具有强大的物质和能量操纵能力，可帮助您突破宇宙本身的界限。",
    "A planet with the sole purpose of housing you and your family.": "一个唯一目的是为您和您的家人提供住所的星球。",
    "A staircase to the all mighty themselves.": "通向万能者的阶梯。",
    "A strange wizard offers you a few secret spells which might be usefull.": "一个奇怪的巫师为您提供了一些可能有用的秘密法术。",
    "A symbiotic relationship that helps you become one with the Void.": "一种共生关系，可帮助您与 Void 融为一体。",
    "A technique designed to manipulate human thought and action against their desire.": "一种旨在操纵人类思想和行动违背其愿望的技术。",
    "abilities.": "能力。",
    "ability and you will gain": "能力，你将获得",
    "ability unlocked!": "能力解锁！",
    "Absolute power corrupts absolutely.": "绝对的权力导致绝对的腐败。",
    "Absolute Wish": "绝对愿望",
    "Abyss Anomaly": "深渊畸体",
    "Abyss God": "深渊之神",
    "Abyss Manipulation": "深渊操纵",
    "Acallaris": "阿卡拉里斯",
    "Adept Mage": "熟练法师",
    "Affects all XP gain": "影响所有 经验 增益",
    "Affects Almightiness XP gain": "影响全能 经验 增益",
    "Affects Dark Magic XP gain": "影响黑魔法 经验 增益",
    "All Seeing Eye": "全视之眼",
    "all XP": "所有经验值",
    "Allows you to shape your own reality within the Void itself.": "允许你在 Void 本身中塑造你自己的现实。",
    "Almightiness": "全能",
    "Almighty Eye": "全能之眼",
    "along with new abilities that will boost you even further in your journey.": "连同新的能力，将在你的旅程中进一步推动你。",
    "and current levels.\n\t\t\t\t\t\t\t\t\t\tHowever, your max levels won't be erased, but instead multiplied with the effect from the": "和当前等级。\n\t\t\t\t\t\t\t\t\t\t但是，你的最高等级不会被删除，而是乘以",
    "Angry Heroes": "愤怒的英雄",
    "Apprentice Mage": "魔法学徒",
    "Archmage": "法宗",
    "Arrow Keys - Menu navigation\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t": "箭头键 - 菜单导航\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t",
    "As the highest rank of T.A.A, all funds go directly to you.": "作为 奥术协会（T.A.A） 的最高级别，所有资金都直接归您所有。",
    "As the highest ranking official, you manage and oversee everything that happens. While your pay is astronomical, so are your expenses.": "作为最高级别的官员，您管理和监督发生的一切。 虽然你的薪水是天文数字，但你的开支也是如此。",
    "Astral Body": "星体",
    "Astral Realm": "星界",
    "Awesome Heroes": "真棒英雄",
    "back!\n\t\t\t\t\t\t\t\t\t\t\t\t": "回来了！\n\t\t\t\t\t\t\t\t\t\t\t\t",
    "Balance": "资金",
    "Based on a": "基于",
    "Battle Tactics": "战斗战术",
    "Beautiful Heroes": "美丽英雄",
    "Being able to exist in multiple parallel timelines and manipulating you parallel selves, influencing their lives as you see fit.": "能够存在于多个平行时间线中并操纵你平行的自我，以你认为合适的方式影响他们的生活。",
    "Bend space and time through forbidden techniques, speeding up your learning processes.": "通过禁止的技术弯曲空间和时间，加快你的学习过程。",
    "Beneath personality and ego lays the source of our deep character, our personhood. Here are the psychic senses, our deep mind and emotions, symbols and inner reality.": "在个性和自我之下是我们深层性格的源泉，即我们的人格。 这里有通灵感官、我们内心深处的思想和情感、符号和内在现实。",
    "Blessed with unparalleled talent, perform unbelievable feats with magic at will. It is said that an archmage has enough destructive power to wipe an empire off the map.": "拥有无与伦比的天赋，随心所欲地施展令人难以置信的魔法壮举。 据说法宗的破坏力足以将一个帝国从地图上抹去。",
    "Blinded By Darkness": "被黑暗蒙蔽了双眼",
    "Blinded by darkness, you can no longer control yourself. You start to destroy everything in existance to calm yourself.": "被黑暗蒙蔽了双眼，你再也无法控制自己。 你开始摧毁现存的一切来让自己平静下来。",
    "Blood Meditation": "血液冥想",
    "Born from chaos when the universe was first created, believed to exist in harmony, balancing evil and good.": "诞生于宇宙最初创造时的混沌之中，被认为和谐存在，平衡邪恶与善良。",
    "Brainwashing": "洗脑",
    "British £sd": "英国英镑",
    "Buy": "买",
    "by": "by",
    "By performing forbidden magic on your subordinates, you can extract every last drop of Essence from them.": "通过对你的部下施展禁忌魔法，你可以从他们身上榨取最后一滴精华。",
    "By possesing the power to partially alter the laws of physics and transceding lower dimensional spaces, your existence becomes never-ending.": "通过拥有部分改变物理定律和超越低维空间的力量，你的存在变得永无止境。",
    "By proving your skills with a bow, you were appointed to lead a small group of archers to ambush your enemies from a distance.": "通过用弓证明你的技能，你被任命带领一小群弓箭手从远处伏击你的敌人。",
    "by x": "由 x",
    "Came into existance long before our universe was created, this strange looking object with no shape radiates unlimited energy.": "在我们的宇宙被创造之前很久就存在了，这个看起来很奇怪的没有形状的物体散发出无限的能量。",
    "Ceaseless Abyss": "无尽深渊",
    "Celestial Powers": "天权",
    "Celestial Robe": "仙袍",
    "Centenary": "百夫长",
    "Challenge 1 Reward: Multiplies happiness by x": "挑战 1 奖励：幸福乘以 x",
    "Challenge 2 Reward: Multiplies income by x": "挑战 2 奖励：收入乘以 x",
    "Challenge 3 Reward: Multiplies time warping by x": "挑战 3 奖励：将时间扭曲乘以 x",
    "Challenge 4 Reward: Multiplies essence gain by x": "挑战4奖励：精华增益乘以x",
    "Challenge 5 Reward: Multiplies evil gain by x": "挑战 5 奖励：邪恶收益乘以 x",
    "Challenge rewards are always active, even in challenges.": "在挑战时，已获得的挑战奖励也是生效的。",
    "Challenges": "挑战",
    "Changelog": "更新日志",
    "Chronomancer": "时光法师",
    "City Ruler": "城市统治者",
    "class category along with": "类类别连同",
    "Click to activate auto-buy": "点击激活自动购买",
    "collapse the universe": "宇宙崩溃",
    "Collapse the universe": "宇宙坍缩",
    "Collapse the universe:": "折叠宇宙：",
    "Color Blind Friendly": "色盲友好",
    "Color scheme": "配色方案",
    "Commander of the Galactic Council grants you the privilege to automatically collect Essence from the nearby planets": "银河委员会指挥官授予您自动从附近行星收集精华的特权",
    "Control the Devil by making him give you even more Evil per second": "通过让他每秒给你更多的邪恶来控制魔鬼",
    "Corrupted": "腐化",
    "Corrupted by Void, you are slowly turning into a slave with no free will, just to serve the Void for the rest of eternity... Can you resist it, or will it consume you forever?": "被虚空腐蚀，你正在慢慢变成一个没有自由意志的奴隶，只为虚空服务一辈子……你能抵抗它，还是它会永远吞噬你？",
    "Cosmic Longevity": "宇宙长寿",
    "Cosmic Recollection": "宇宙回忆",
    "Cost:": "成本：",
    "Create your own pocket dimension where centuries go by in mere seconds.": "创建您自己的口袋维度，几个世纪在短短几秒钟内流逝。",
    "Creator of everything.": "万物的创造者。",
    "Creator of the Void, a vast canvas of blackness and nothingness, in which the concept of its existence defies all logic. Nothing will escape you.": "虚空的创造者，一片黑暗和虚无的巨大画布，其存在的概念违背了所有逻辑。 没有什么能逃过你。",
    "Currency notation": "货币符号",
    "Current challenge:": "当前的挑战：",
    "Current reward: Multiplies essence gain by x": "当前奖励：精华获取量乘以x",
    "Current reward: Multiplies evil gain by x": "当前奖励：将邪恶收益乘以 x",
    "Current reward: Multiplies happiness by x": "当前奖励：将幸福乘以 x",
    "Current reward: Multiplies income by x": "当前奖励：收入乘以 x",
    "Current reward: Multiplies time warping by x": "当前奖励：将时间扭曲乘以 x",
    "Damned soul... a shadow of your former self, lingering between realms and consumed by void... Can you ever find peace?": "该死的灵魂……你以前的自己的影子，徘徊在各个领域之间，被虚空吞噬……你能找到平静吗？",
    "Dark": "深色",
    "Dark Influence": "黑暗影响",
    "Dark Knowledge": "黑暗知识",
    "Dark Magic": "黑暗魔法",
    "Dark Magician": "黑暗魔法师",
    "Dark Matter": "暗物质",
    "Dark Matter Harvester": "暗物质收割机",
    "Dark Matter Millionaire": "暗物质百万富翁",
    "Dark Matter Mining": "暗物质开采",
    "Dark Matter:": "暗物质：",
    "Dark Milestones": "黑暗里程碑",
    "Dark Orb": "黑暗宝珠",
    "Dark Orb Generator": "黑暗宝珠生成器",
    "Dark Orbiter": "黑暗轨道飞行器",
    "Dark Orbs": "黑暗宝珠",
    "Dark Orbs:": "黑暗宝珠：",
    "Dark Prince": "黑暗王子",
    "Dark Ruler": "黑暗统治者",
    "Darkness": "黑暗",
    "days (game time).": "天（游戏时间）。",
    "days ago.": "几天前。",
    "Deal with the Devil": "对付魔鬼",
    "Demon Training": "恶魔训练",
    "Demon's Wealth": "恶魔的财富",
    "Dirty Heroes": "肮脏的英雄",
    "Does time matter now?": "现在时间重要吗？",
    "Each day, you are succumbing to the Void more and more. Can you hold onto your humanity for a bit longer, or will you let the Void devour you?": "每一天，你都越来越屈服于虚空。 你能再坚持你的人性，还是让虚空吞噬你？",
    "Embrace evil:": "拥抱邪恶：",
    "Epiphany": "顿悟",
    "essence": "本质",
    "Essence might become the new gold due to mass adoption.": "由于大规模采用，精华可能会成为新的黄金。",
    "Essence Milestones": "精华里程碑",
    "essence/s was at": "本质是在",
    "essence/s. Maximum": "精华 最大限度",
    "Every active Great job or skill will increase Essence gain a bit.": "每个活跃的伟大职业或技能都会增加一点精华获取。",
    "Evil Incarnate": "邪恶化身",
    "evil/s was at": "邪恶/秒 在",
    "evil/s. Maximum": "邪恶/秒。 最大限度",
    "Exit challenge": "退出挑战",
    "Expense:": "支出：",
    "Exploit the unlimited potential of multiverse energies and collect its resources.": "开发多元宇宙能量的无限潜力并收集其资源。",
    "Explosion of the universe": "宇宙大爆炸",
    "Extremely powerful being with tremedous telekinetic powers and the ability to rearrange the molecular structure of matter and energy, even up to cosmic scale.": "极其强大的存在，具有强大的心灵感应能力，能够重新排列物质和能量的分子结构，甚至可以达到宇宙规模。",
    "Faint Hope": "渺茫的希望",
    "Feared by nations, obliterate entire armies in a blink of an eye. Roughly every century, only one holy knight is worthy of receiving such an esteemed title.": "万国畏惧，转眼间歼灭全军。 几乎每个世纪，只有一位圣骑士配得上这样尊贵的称号。",
    "Font size": "字体大小",
    "for your classes and abilities equivalent to:": "你的工作和技能将会获得经验乘数，公式为：",
    "Forged from void dust and dark matter, this blade can slash through dimensional barriers. It's a weapon of choice for every Void Reaver.": "这把刀刃由虚空尘埃和暗物质锻造而成，可以斩断次元壁垒。 它是每个虚空掠夺者的首选武器。",
    "From the time the universe was born. Can create more small universes.": "从宇宙诞生之日起。 可以创造出更多的小宇宙。",
    "Funny Heroes": "有趣的英雄",
    "Furious Heroes": "狂暴英雄",
    "gain by": "获得",
    "gain by x": "增益 x",
    "Galactic Command": "银河司令部",
    "Galactic Council": "银河委员会",
    "Galactic Emperor": "银河皇帝",
    "Galactic Throne": "银河王座",
    "Galaxy": "星系",
    "Galaxy Filament": "银河灯丝",
    "Generates": "产生",
    "Generates an innate armor as a part of you body, which is resistant to attacks, harm or pain.": "生成一个与生俱来的盔甲作为你身体的一部分，它可以抵抗攻击、伤害或疼痛。",
    "get your": "拿你的",
    "Git游戏": "Git 游戏",
    "Github page": "Github页面",
    "God's Blessings": "上帝的祝福",
    "Gotta be fast": "一定要快",
    "Grand Palace": "大宫殿",
    "Gross Income": "总收入",
    "Grow and culture the evil within you through the sacrifice of other living beings, drastically increasing evil gain.": "通过牺牲其他生物来滋长和培养你内心的邪恶，大大增加邪恶的收益。",
    "Happiness:": "幸福：",
    "Harvest the universe to extract even more Dark Matter from it.": "收割宇宙以从中提取更多的暗物质。",
    "Helps you shape and manipulate void matter, even transmute and rebuild it into anything of your choosing.": "帮助你塑造和操纵虚空物质，甚至将其转化并重建为你选择的任何东西。",
    "Heroic Milestones": "英雄里程碑",
    "Higher Dimensions": "更高维度",
    "Highway to hell": "通向地狱的公路",
    "If thou gaze long into an abyss, the abyss will also gaze into thee.": "如果你长时间凝视深渊，深渊也会凝视你。",
    "If you decide to": "如果你决定",
    "Immortal Ruler": "不朽的统治者",
    "Imperator": "法皇",
    "In a trance like state, you feel the Void amplifying your thoughts, perception, memories, emotions and personality.": "在恍惚状态下，你会感觉到虚空在放大你的思想、感知、记忆、情感和个性。",
    "in this collapse.": "在这场崩溃中。",
    "in this embrace.": "在这个怀抱中。",
    "in this life.": "在这一生中。",
    "in this transcension.": "在这种超越中。",
    "Inferno": "地狱火",
    "Large House": "大房子",
    "Larger": "更大",
    "Lazy Heroes": "懒英雄",
    "Lengthen your lifespan drastically beyond comprehension by harnessing ethereal energy.": "通过利用空灵能量，大大延长您的寿命，超出理解范围。",
    "Lets you see memories, remember images, and even see new pictures and ideas.": "让您看到回忆、记住图像，甚至看到新的图片和想法。",
    "Lieutenant General": "中将",
    "Life coach": "人生导师",
    "Life Essence": "生命精华",
    "Life is valueable": "生命是有价值的",
    "Light": "浅色",
    "Links": "链接",
    "Magic Eye": "魔眼",
    "Mana Control": "魔力控制",
    "Master Wizard": "大法师",
    "Mastery is achieved when 'telling time' becomes 'telling time what to do'.": "当“告诉时间”变成“告诉时间做什么”时，就达到了精通。",
    "Max": "历史最高等级",
    "Maybe there is hope?": "也许还有希望？",
    "Medieval": "中世纪",
    "Milestones": "里程碑",
    "millennium": "",
    "Mind Control": "精神控制",
    "Mind Release": "心灵释放",
    "Mind's Eye": "心灵的眼球",
    "Mine a huge amount of Dark Matter from each planet you visit.": "从您访问的每个星球上开采大量暗物质。",
    "mod\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t": "mod\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t",
    "Modern $": "现代 $",
    "Multiverse Fragment": "多元宇宙碎片",
    "Muscle Memory": "肌肉记忆",
    "Nation Ruler": "国家统治者",
    "Net:": "净赚：",
    "Never ending torture, you swore to serve the Void for the rest of your existence.": "永无休止的折磨，你发誓终生为虚空服务。",
    "New Beginning": "新的开始",
    "No one dares to challenge your rule when ruling with an iron fist.": "铁腕统治，谁也不敢挑战你的统治。",
    "NOT": "不是",
    "Nova": "新星",
    "Number notation": "数字符号",
    "Obliterate squadrons of enemy soldiers in one go with extraordinary proficiency, while wielding a magically imbued blade. Such a feared unit on the battlefield is paid extremely well.": "挥舞着一把充满魔法的刀刃，以非凡的熟练度一次性消灭敌方士兵中队。 这样一个在战场上令人畏惧的单位，待遇非常好。",
    "Observable Universe": "可观测宇宙",
    "Observatory": "天文台",
    "One Above All": "至高无上",
    "One of the largest known structures of the universe, containing dozens of superclusters and millions of galaxies.": "已知最大的宇宙结构之一，包含数十个超星系团和数百万个星系。",
    "Parallel Universe": "平行宇宙",
    "Personal Squire": "私人扈从",
    "Planet": "行星",
    "Pocket Dimension": "口袋空间",
    "Predating our own universe, the Void has an unlimited amount of space for your belongings, if you are willing to submit to it.": "在我们自己的宇宙之前，虚空有无限的空间来存放你的物品，如果你愿意服从它的话。",
    "Primordial being that predate the universe, involved with the creation of life and powerful beyond mortal comprehension, existing as myths to the oldest species in the universe.": "原始存在早于宇宙，参与生命的创造，强大到超出凡人的理解，作为宇宙中最古老物种的神话存在。",
    "Purest version of void created material; a teaspoon of it is as heavy as a small planet.": "最纯净的虚空创造材料； 一茶匙它和一个小行星一样重。",
    "Reduces Dark Magic and Almightiness XP effect enormously, max level reduces XP gain and happiness is reduced by ^": "极大地降低黑魔法和全能 XP 效果，最高级别减少 XP 增益，幸福减少 ^",
    "Reduces happiness by ^": "减少幸福^",
    "Reduces income by ^": "减少收入^",
    "Reduces time warping by ^": "减少时间扭曲 ^",
    "Reduces your lifespan by ^0.72, happiness does nothing and Dark Magic XP effect is always": "将你的寿命减少 ^0.72，幸福无济于事，黑魔法 XP 效果始终存在",
    "Reel in various fish and sell them for a handful of coins. A relaxing but still poor paying job.": "卷入各种鱼并以少量硬币出售。 一份轻松但薪水仍然很低的工作。",
    "Reset Skills": "重置技能",
    "Reward: Multiplies essence gain by x": "奖励：精华增益乘以x",
    "Reward: Multiplies evil gain by x": "奖励：邪恶收益乘以x",
    "Reward: Multiplies happiness by x": "奖励：将幸福乘以 x",
    "Reward: Multiplies income by x": "奖励：将收入乘以 x",
    "Reward: Multiplies time warping by x": "奖励：将时间扭曲乘以 x",
    "Reward: Multiply": "奖励：倍增",
    "Rise of Great Heroes": "英雄崛起",
    "Ruling the universe allows you to collect more Dark Matter from your subordinates.": "统治宇宙可以让你从你的下属那里收集更多的暗物质。",
    "Sapphire Charm": "蓝宝石护身符",
    "Scared Heroes": "害怕的英雄",
    "Scientific": "科学",
    "Screaming into existence, you become a manifestation of the unknowable nothingness that lies beyond.": "尖叫着存在，你成为超越不可知的虚无的体现。",
    "Sealed for a very long time, you utilize these forbidden texts for your own personal gain.": "封存了很长时间，你利用这些禁书来谋取私利。",
    "Self-contained plane of existence, co-existing with one's own, helping you restore fragments of your forgotten power.": "独立的存在位面，与自己共存，帮助您恢复被遗忘的力量碎片。",
    "Shady deals with the Devil grant you a huge Evil bonus.": "Shady Deals with the Devil 为您提供巨大的邪恶奖励。",
    "Shortcuts": "快捷方式",
    "Sigma Proioxis": "西格玛计划",
    "Small Palace": "小型宫殿",
    "Smaller": "更小",
    "Something tells you that the amulet might evolve after living for": "某个存在告诉你，如果你能活过两个世纪，这个护身符还可能进化出新的能力...（译者注：原本是1倍；如果最大等级为10级，则会获得1+10/10=2倍经验；如果最大等级为100级，则会获得1+100/10=11倍经验）",
    "Spacebar - Pause": "空格键 - 暂停",
    "Spaceship": "飞船",
    "Specialize in harnessing temporal energies that alter the flow of time with supernatural divinations and otherwordly expertise.": "专注于利用超自然占卜和其他专业知识改变时间流逝的时间能量。",
    "Speed is life": "速度就是生命",
    "Speed speed speed": "速度速度速度",
    "Stairway to heaven": "通往天堂的阶梯",
    "Standard": "标准",
    "Start a new era of Dark Matter.": "开启暗物质的新时代。",
    "Starting a challenge will": "开始挑战将",
    "Steel Longsword": "钢长剑",
    "Stellar Neighborhood": "恒星社区",
    "Sticky sidebar": "固定侧边栏",
    "Study Desk": "书桌",
    "Study the theory of mana and practice basic spells. There is minor pay to cover living costs; however, this is a necessary stage in becoming a mage.": "研究法力理论并练习基本法术。 支付生活费用的工资很少； 但是，这是成为法师的必经阶段。",
    "Supercluster": "超星系团",
    "T.A.A & Magic": "奥术协会（T.A.A） & 魔法",
    "Tapping into the powers of the Void while combining them with evil grants you an unlimited potential.": "利用 Void 的力量，同时将它们与邪恶结合，赋予您无限的潜力。",
    "Temporal Dimension": "时间维度",
    "ten millennia": "十千年",
    "The amulet might transform even further after living for a": "如果你活到整整1000年，这个护身符可能会发生进一步的变化",
    "The amulet will reach its final form after": "护身符将在之后达到最终形态",
    "The Devil inside you": "你内心的恶魔",
    "The devil invites you to his palace of terror.": "魔鬼邀请你到他的恐怖宫殿。",
    "The Eye in your Amulet shines like a star.": "你护身符中的眼球像星星一样闪耀。",
    "The Eye in your Amulet starts to glow.": "护身符中的眼球开始发光。",
    "The more you advance in the challenge, the higher the reward.": "您在挑战中达成的目标越多，奖励就越高。",
    "The most powerful and essential equipment of any Celestial. Acts as a source of infinite power.": "任何 Celestial 中最强大、最重要的装备。 作为无限力量的源泉。",
    "The power to fulfill absolutely any and all wishes without any limitations.": "能够毫无限制地实现任何和所有愿望的力量。",
    "The Void": "虚空",
    "There are few who may tread the paths between worlds, these powers grant you an ability to generate fields of void energy that devour all living things.": "很少有人可以踏上世界之间的道路，这些力量赋予你产生吞噬所有生物的虚空能量场的能力。",
    "This secret spell will help you reach your quest to become the first Dark Matter millionaire.": "这个秘密咒语将帮助您实现成为第一个暗物质百万富翁的目标。",
    "Time is limited... Even as the ruler of the universe.": "时间有限……即使身为宇宙主宰。",
    "times.": "次。",
    "Tired Heroes": "疲倦的英雄",
    "Total Hero XP multiplier is": "总英雄 XP 乘数是",
    "Town Ruler": "镇长",
    "transcend": "超越",
    "Transcend": "超越",
    "Transcend will only appear if you have the": "只有当你有",
    "Transcend:": "超越：",
    "Transcendent Master": "超凡大师",
    "Try to upgrade One Above All to level": "尝试升级至高无上的水平",
    "Under the supervision of a skilled mage, perform basic spells against enemies in battle. Generous pay will be provided to cover living costs.": "在熟练的法师的监督下，在战斗中对敌人施展基本法术。 将提供丰厚的报酬以支付生活费用。",
    "Universal Ruler": "万能尺",
    "Universe Fragment": "宇宙碎片",
    "Unknown how or when the Void realm came into existence, containing elements which don’t exist outside of its dimensional plane are now all to your disposal": "未知 Void 领域是如何或何时出现的，包含在其维度平面之外不存在的元素现在都由你支配",
    "Unlocks the ability to reset for Dark Matter": "解锁重置暗物质的能力",
    "Used for observing terrestrial, marine and celestial events.": "用于观测陆地、海洋和天体事件。",
    "Used to buy items in the Dark Matter shop": "用于在暗物质商店购买物品",
    "Using some wizardry you can improve your Dark Orb generators massively.": "使用一些魔法，您可以极大地改进您的 Dark Orb 生成器。",
    "Veteran Knight": "资深骑士",
    "Veteran Knight lvl": "资深骑士等级",
    "Void Amplification": "虚空增幅",
    "Void Armor": "虚空铠甲",
    "Void Blade": "虚空之刃",
    "Void Dust": "虚空之尘",
    "Void Embodiment": "虚空化身",
    "Void Fiend": "虚空恶魔",
    "Void Influence": "虚空势力",
    "Void Lord": "虚空领主",
    "Void Manipulation": "虚空操纵",
    "Void Necklace": "虚空项链",
    "Void Orb": "虚空宝珠",
    "Void Realm": "虚空境界",
    "Void Reaver": "虚空掠夺者",
    "Void Slave": "虚空奴隶",
    "Void Symbiosis": "虚空共生",
    "Void Universe": "虚无宇宙",
    "Void Wraith": "虚空幽魂",
    "when performing a Dark Matter or lower reset": "执行暗物质或更低重置时",
    "When the orb touches non void entities, it instantly disintegrates them by harnessing its power from Void realm.": "当球体接触到非虚空实体时，它会利用虚空领域的力量立即瓦解它们。",
    "which will boost you much further in your journey across the multiverse.": "这将进一步推动你穿越多元宇宙的旅程。",
    "With the powers bestowed upon you by an unknown entity, you wander around, visiting places revered and feared in search of answers.": "凭借未知实体赋予你的力量，你四处游荡，造访受人尊敬和恐惧的地方以寻找答案。",
    "years\n\t\t\t\t\t\t": "年\n\t\t\t\t\t\t",
    "Yin Yang": "阴阳",
    "You are at the last level of Hell. What is next?": "你在地狱的最后一层。 下一步是什么？",
    "You are starting to become way too powerful. The end of the universe may be near...": "你开始变得太强大了。 宇宙的尽头可能已经临近...",
    "You become an inquisitive yet putrid creature that siphons life from everything around you.": "你变成了一个好奇而又腐败的生物，从你周围的一切中吸取生命。",
    "You become one with everything.": "你与一切合而为一。",
    "You can affect the speed of the universe with your gigantic amount of Dark Matter.": "你可以用大量的暗物质影响宇宙的速度。",
    "You can increase your intelligence at an alarming rate due to your access to all libraries in the universe.": "由于您可以访问宇宙中的所有图书馆，您可以以惊人的速度提高您的智力。",
    "You can only choose 1 upgrade in each category; pick wisely. You can reset the skills, but you will": "每个类别只能选择1个升级； 明智地选择。 你可以重置技能，但你会",
    "You did it! You finally rule the entire universe...or do you?": "你做到了！ 你终于统治了整个宇宙......或者你呢？",
    "You gazed into the dark heart of the Void long enough to become one of the most powerful and feared beings. All lesser void creatures are at your command.": "你凝视虚空的黑暗之心足够长的时间，成为最强大和最令人恐惧的存在之一。 所有次级虚空生物都听从你的指挥。",
    "You have became the very thing you swore to destroy.": "你已经成为你发誓要摧毁的东西。",
    "You have collapsed the universe": "你让宇宙坍塌",
    "You have embraced evil": "你拥抱了邪恶",
    "You have only one goal: ruling this universe till infinity.": "你只有一个目标：统治这个宇宙直到无限。",
    "You have played for": "你玩过",
    "You have seen it all, from the very beginning to the very end.": "你已经看到了这一切，从头到尾。",
    "You have spent": "你花了",
    "You have touched the eye": "你触动了眼球",
    "You have transcended": "你超越了",
    "You have unlocked": "你已经解锁",
    "You made a deal with the Devil.": "你和魔鬼做了一笔交易。",
    "You reign the whole nation. While your riches may be corrupted, everything you see belongs to you.": "你统治整个国家。 虽然您的财富可能会被腐蚀，但您所看到的一切都属于您。",
    "You rule your very own community in your small town, owning multiple establishments.": "你在你的小镇上统治着你自己的社区，拥有多个机构。",
    "You sit on your throne, overseeing the existence itself.": "你坐在你的宝座上，监督着存在本身。",
    "You started playing the game on": "您开始玩游戏的时间",
    "You surrender yourself to the Void, making it easier to take control of you.": "你将自己臣服于虚空，这样更容易控制你。",
    "You wield an unlimited power, making you unstoppable. By ruling with an iron fist, everyone in the Arcane Association has to obey your commands.": "你拥有无限的力量，让你势不可挡。 以铁腕统治，奥术协会的每一个人都必须服从你的命令。",
    "You've mastered Transcendence.": "你已经掌握了超越。",
    "You've opened a portal to Hell.": "你打开了地狱之门。",
    "Your age has met your lifespan; use the amulet to rebirth before you pass away": "你的年龄已经满足了你的寿命； 在你去世之前使用护身符重生",
    "your coins, levels and max levels.": "您的硬币、等级和最高等级。（译者注：推荐在拥抱邪恶后进入挑战）",
    "Your existance has spanned": "你的存在已经跨越",
    "Your fastest collapse is in": "你最快的崩溃是在",
    "Your fastest embrace is in": "你最快的拥抱就在",
    "Your fastest touch is in": "你最快的接触是在",
    "Your fastest transcension is in": "你最快的超越是在",
    "Your greatest debt": "你最大的债务",
    "Your own personal cosmic house, able to travel anywhere in the universe at 99.99% of the speed of light.": "你自己的私人宇宙之家，能够以 99.99% 的光速在宇宙中的任何地方旅行。",
    "In challenge:": "挑战中",
    "Required:": "要求：",
    "- \n\t\t\t\t\t\t\t\t\t\t\t\t\tMultiply": "- \n\t\t\t\t\t\t\t\t\t\t\t\t\t乘以",
    "Centenary lvl": "百夫长 等级",
    "unknown": "未知",
    "Lieutenant General lvl": "中将等级",
    "  Save copied to clipboard!": "存档已复制到剪切板！",
    "Void Lord lvl": "虚空领主等级",
    "An unhappy life": "不幸的生活",
    "Rich and the poor": "富人和穷人",
    "Unlocks Dark Matter": "解锁暗物质",
    "Unlocks Dark Matter Skills": "解锁暗物质技能",
    "Automatically gain max levels": "自动获得最高等级",
    "Automatically gain max levels at age": "自动获得最高等级当年龄达到",
    "Heroic jobs, skills and items are unlocked": "解锁英雄职业、技能和物品",
    "Makes Hell Portal even stronger": "让地狱传送门更强大",
    "Multiply Dark Matter gain by": "将暗物质增益乘以",
    "Multiply Dark Orb gain by 1e": "将 黑暗宝珠 增益乘以 1e",
    "Multiply Darkness xp gain by 1e": "将黑暗经验 增益乘以 1e",
    "Multiply Essence gain by": "将精华增益乘以",
    "Multiply Evil gain by 1e": "将邪恶增益乘以 1e",
    "Multiply Time Warping and Lifespan by": "将时间扭曲和寿命乘以",
    "Multiply your lifespan by 1e": "将你的寿命乘以 1e",
    "Passively gain a huge amount of Evil": "被动获得大量邪恶",
    "Passively gain a small amount of Essence": "被动获得少量精华",
    "Passively gain a small amount of Evil": "被动获得少量邪恶",
    "Required": "要求",
    "Dance with the devil": "与魔鬼共舞",
    "Legends never die": "传奇永不消逝",
    "Time does not fly": "时间不会飞",
    "Eternal Wanderer": "永恒浪客",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",

    //原样
    '2 whole centuries': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": " ",
    "   ": " ",
    "  ": " ",
    " ": " ",
    "\n                            ": "\n                            ",
    "\t\t\t\t\t\t\t\t\t\t\t": "\t\t\t\t\t\t\t\t\t\t\t",
    "\n\t\t\t\t\t\t\t\t\t\t": "\n\t\t\t\t\t\t\t\t\t\t",
    "\n\t\t\t\t\t\t": "\n\t\t\t\t\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\t\t\t": "\t\t\t",
    "\t\t": "\t\t",
    "\t": "\t",
    ", \n\t\t\t\t\t\t\t\t\t\t\t\t\t": ", \n\t\t\t\t\t\t\t\t\t\t\t\t\t",
    "Battle tactics level ": "战斗战术等级 ",
    "Veteran knight level ": "资深骑士等级 ",
    "Strength level ": "力量等级 ",
    "Farmer level ": "农民等级 ",
    "Productivity level ": "效率等级 ",
    "Concentration level ": "专注等级 ",
    "Beggar level ": "乞丐等级 ",
    "Miner level ": "矿工等级 ",
    "Fisherman level ": "渔夫等级 ",
    "Meditation level ": "冥想等级 ",
    "Squire level ": "护卫等级 ",
    "Veteran footman level ": "资深步兵等级 ",
    "Elite knight level ": "骑士等级 ",
    "Knight level ": "骑士等级 ",
    "Holy knight level ": "圣骑士等级 ",
    "Footman level ": "步兵等级 ",
    "Blacksmith level ": "铁匠等级 ",
    "Mana control level ": "法力控制等级 ",
    "Bargaining level ": "讨价还价等级 ",
    "Mage level ": "法师等级 ",
    "Evil control level ": "邪恶控制等级 ",
    "Chairman level ": "会长等级 ",
    "Dark influence level ": "黑暗影响等级 ",
    "Time warping level ": "时间扭曲等级 ",
    "Wizard level ": "巫师等级 ",
    "Student level ": "学生等级 ",
    "Master wizard level ": "大法师等级 ",
    "Intimidation level ": "威胁等级 ",
    "Legendary knight level ": "传奇骑士等级 ",
    "Immortality level ": "永生等级 ",
    "Demon training level ": "魔鬼训练等级 ",
    "Apprentice mage level ": "魔法学徒等级 ",
    "Cost growth:": "成本成长:",
    "Grand Duke level ": "大公等级",
    "Arch Duke level ": "大公爵等级",
    "Lord level ": "领主等级",
    "Sophomore lvl ": "大二等级",
    "Junior lvl ": "初级等级",
    "Junior Caretaker lvl ": "初级看守等级",
    "Freshman lvl ": "大一等级",
    "Count lvl ": "伯爵等级",
    "Baron lvl ": "男爵等级",
    "Baronet lvl ": "准男爵等级",
    "Grand Duke lvl ": "大公等级",
    "Senior lvl ": "高级等级",
    "Probation level ": "实习生等级",
    "Lead Caretaker lvl ": "看守主管等级",
    "Duke level ": "公爵等级",
    "Probation level ": "实习生等级",
    "Unusual Insight level ": "非凡洞察力等级",
    "Eternal Wanderer": "永恒流浪者",
    "Goal: ": "目标: ",
    "Version: ": "版本：",
    "Lieutenant General lvl ": "中将 等级 ",
    "Great ": "伟大的",
    "Abyss God lvl ": "深渊之神等级 ",
    "Beggar lvl ": "乞讨等级 ",
    "Void Slave lvl": "虚空奴隶等级",
    "Imperator lvl": "法皇等级",
    "Abyss Anomaly lvl": "深渊畸体等级",
    "Master Wizard lvl": "大法师等级",
    'Bargaining lvl': '讨价还价等级',
    'Battle tactics lvl': '战斗战术等级',
    'Fisherman lvl': '渔夫等级',
    'Strength lvl': '力量等级',
    'Productivity lvl': '效率等级',
    'Squire lvl': '护卫等级',
    'Meditation lvl': '冥想等级',
    'Miner lvl': '矿工等级',
    'Veteran knight lvl': '资深骑士等级',
    'Merchant lvl': '商人等级',
    'Footman lvl': '步兵等级',
    'Veteran footman lvl': '资深步兵等级',
    'Knight lvl': '骑士等级',
    'Blacksmith lvl': '铁匠等级',
    'Mana control lvl': '法力控制等级',
    'Muscle memory lvl': '肌肉记忆等级',
    'Elite knight lvl': '精英骑士等级',
    'Student lvl': '学生等级',
    'Mage lvl': '法师等级',
    'Wizard lvl': '巫师等级',
    'Intimidation lvl': '威胁等级',
    'Time warping lvl': '时间扭曲等级',
    'Evil control lvl': '邪恶控制等级',
    'Dark influence lvl': '黑暗影响等级',
    'Chairman lvl': '会长等级',
    'Legendary knight lvl': '传奇骑士等级',
    'Demon training lvl': '魔鬼训练等级',
    'Master wizard lvl': '大法师等级',
    'Immortality lvl': '永生等级',
    'Holy knight lvl': '圣骑士等级',
    'Holy Knight lvl': '圣骑士等级',
    'Apprentice mage lvl': '魔法学徒等级',
    "One Above All lvl ": "至高无上等级",
    "Void Reaver lvl": "虚空掠夺者等级",
    "Sigma Proioxis lvl": "西格玛计划等级",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": " ",
    "  ": " ",
    " ": " ",
    "\n\t\t\t\t\t\t\t\t\t\t\t\t\t": "\n\t\t\t\t\t\t\t\t\t\t\t\t\t",
    "\n\t\t\t\t\t\t\t\t\t\t": "\n\t\t\t\t\t\t\t\t\t\t",
    "\n\t\t\t\t\t\t\t\t": "\n\t\t\t\t\t\t\t\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^x?\d+(\.\d+)?[A-Za-z%]{0,2}(\s.C)?\s*$/, //12.34K,23.4 °C
    /^x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /^\s*$/, //纯空格
    /^\d+(\.\d+)?[A-Za-z]{0,2}.?\(?([+\-]?(\d+(\.\d+)?[A-Za-z]{0,2})?)?$/, //12.34M (+34.34K
    /^(\d+(\.\d+)?[A-Za-z]{0,2}\/s)?.?\(?([+\-]?\d+(\.\d+)?[A-Za-z]{0,2})?\/s\stot$/, //2.74M/s (112.4K/s tot
    /^\d+(\.\d+)?(e[+\-]?\d+)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?$/, //2.177e+6 (+4.01+4
    /^(\d+(\.\d+)?(e[+\-]?\d+)?\/s)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?\/s\stot$/, //2.177e+6/s (+4.01+4/s tot
];
var cnExcludePostfix = [
    /:?\s*x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /:?\s*x?\d+(\.\d+)?[A-Za-z]{0,2}$/, //: 12.34K, x1.5
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加多空格：\n(.+)
var cnRegReplace = new Map([
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^Adept Mage ([\d\.,]+)\/$/, '熟练法师 $1/'],
    [/^Battle Tactics ([\d\.,]+)\/$/, '战斗战术 $1/'],
    [/^Student ([\d\.,]+)\/$/, '学生 $1/'],
    [/^Time Loop ([\d\.,]+)\/$/, '时间循环 $1/'],
    [/^Meditation ([\d\.,]+)\/$/, '冥想 $1/'],
    [/^Dark Knowledge ([\d\.,]+)\/$/, '黑暗知识 $1/'],
    [/^Meditation ([\d\.,]+)\/([\d\.,]+),$/, '冥想 $1/$2，'],
    [/^All Seeing Eye ([\d\.,]+)\/([\d\.,]+),$/, '全视之眼 $1/$2，'],
    [/^Void Symbiosis ([\d\.,]+)\/([\d\.,]+),$/, '虚空共生 $1/$2，'],
    [/^Battle Tactics ([\d\.,]+)\/([\d\.,]+),$/, '战斗战术 $1/$2，'],
    [/^Battle Tactics ([\d\.,]+)\/([\d\.,]+), Footman ([\d\.,]+)\/$/, '战斗战术 $1/$2，步兵 $3/'],
    [/^Battle Tactics ([\d\.,]+)\/([\d\.,]+), Centenary ([\d\.,]+)\/$/, '战斗战术 $1/$2，百夫长 $3/'],
    [/^Dark Magician ([\d\.,]+)\/$/, '黑暗魔法师 $1/'],
    [/^Dark Prince ([\d\.,]+)\/$/, '黑暗王子 $1/'],
    [/^Chronomancer ([\d\.,]+)\/$/, '时光法师 $1/'],
    [/^Dark Influence ([\d\.,]+)\/$/, '黑暗影响 $1/'],
    [/^Acallaris ([\d\.,]+)\/$/, '阿卡拉里斯 $1/'],
    [/^Eternal Wanderer ([\d\.,]+)\/$/, '永恒流浪者 $1/'],
    [/^Essence Collector ([\d\.,]+)\/$/, '精华收集器 $1/'],
    [/^Brainwashing ([\d\.,]+)\/$/, '洗脑 $1/'],
    [/^Cosmic Recollection ([\d\.,]+)\/$/, '宇宙回忆 $1/'],
    [/^Cosmic Longevity ([\d\.,]+)\/$/, '宇宙长寿 $1/'],
    [/^Ceaseless Abyss ([\d\.,]+)\/$/, '无尽深渊 $1/'],
    [/^Abyss Manipulation ([\d\.,]+)\/$/, '深渊操纵 $1/'],
    [/^Abyss God ([\d\.,]+)\/$/, '深渊之神 $1/'],
    [/^Galactic Command ([\d\.,]+)\/$/, '银河司令部 $1/'],
    [/^Sigma Proioxis ([\d\.,]+)\/$/, '西格玛计划 $1/'],
    [/^Sigma Proioxis ([\d\.,]+)\/([\d\.,]+)$/, '西格玛计划 $1/$2'],
    [/^Void Wraith ([\d\.,]+)\/$/, '虚空幽魂 $1/'],
    [/^Void Symbiosis ([\d\.,]+)\/$/, '虚空共生 $1/'],
    [/^Void Reaver ([\d\.,]+)\/$/, '虚空掠夺者 $1/'],
    [/^Void Fiend ([\d\.,]+)\/$/, '虚空恶魔 $1/'],
    [/^Void Embodiment ([\d\.,]+)\/$/, '虚空化身 $1/'],
    [/^Void Amplification ([\d\.,]+)\/$/, '虚空增幅 $1/'],
    [/^Mind Release ([\d\.,]+)\/$/, '心灵释放 $1/'],
    [/^Abyss Anomaly ([\d\.,]+)\/$/, '深渊畸体 $1/'],
    [/^Absolute Wish ([\d\.,]+)\/$/, '绝对愿望 $1/'],
    [/^Concentration ([\d\.,]+)\/$/, '专注 $1/'],
    [/^Concentration ([\d\.,]+)\/([\d\.,]+), Meditation ([\d\.,]+)\/$/, '专注 $1/$2，冥想 $3/'],
    [/^Concentration ([\d\.,]+)\/([\d\.,]+), Strength ([\d\.,]+)\/$/, '专注 $1/$2，力量 $3/'],
    [/^Knight ([\d\.,]+)\/$/, '骑士 $1/'],
    [/^Productivity ([\d\.,]+)\/([\d\.,]+),$/, '效率 $1/$2，'],
    [/^Mana Control ([\d\.,]+)\/([\d\.,]+),$/, '法力控制 $1/$2，'],
    [/^Mana Control ([\d\.,]+)\/$/, '法力控制 $1/'],
    [/^Apprentice Mage ([\d\.,]+)\/$/, '魔法学徒 $1/'],
    [/^Miner ([\d\.,]+)\/$/, '矿工 $1/'],
    [/^Imperator ([\d\.,]+)\/$/, '法皇 $1/'],
    [/^Squire ([\d\.,]+)\/$/, '护卫 $1/'],
    [/^Void Lord ([\d\.,]+)\/$/, '虚空领主 $1/'],
    [/^Void Slave ([\d\.,]+)\/$/, '虚空奴隶 $1/'],
    [/^Temporal Dimension ([\d\.,]+)\/$/, '时间维度 $1/'],
    [/^Blacksmith ([\d\.,]+)\/$/, '铁匠 $1/'],
    [/^Yin Yang ([\d\.,]+)\/$/, '阴阳 $1/'],
    [/^Universal Ruler ([\d\.,]+)\/$/, '万能尺 $1/'],
    [/^Footman ([\d\.,]+)\/$/, '步兵 $1/'],
    [/^Farmer ([\d\.,]+)\/$/, '农夫 $1/'],
    [/^Archmage ([\d\.,]+)\/$/, '法宗 $1/'],
    [/^Strength ([\d\.,]+)\/$/, '力量 $1/'],
    [/^Strength ([\d\.,]+)\/([\d\.,]+), Miner ([\d\.,]+)\/$/, '力量 $1/$2，矿工 $3/'],
    [/^Strength ([\d\.,]+)\/([\d\.,]+), Knight ([\d\.,]+)\/$/, '力量 $1/$2，骑士 $3/'],
    [/^Strength ([\d\.,]+)\/([\d\.,]+), Squire ([\d\.,]+)\/$/, '力量 $1/$2，护卫 $3/'],
    [/^Strength ([\d\.,]+)\/([\d\.,]+), Veteran footman ([\d\.,]+)\/$/, '力量 $1/$2，资深步兵 $3/'],
    [/^Void Embodiment ([\d\.,]+)\/([\d\.,]+), Void Lord ([\d\.,]+)\/$/, '虚空化身 $1/$2，虚空领主 $3/'],
    [/^All Seeing Eye ([\d\.,]+)\/([\d\.,]+), Concentration ([\d\.,]+)\/([\d\.,]+), Chairman ([\d\.,]+)\/$/, '全视之眼 $1/$2，专注 $3/$4，会长 $5/'],
    [/^Bargaining ([\d\.,]+)\/$/, '讨价还价 $1/'],
    [/^Bargaining ([\d\.,]+)\/([\d\.,]+), Blacksmith ([\d\.,]+)\/$/, '讨价还价 $1/$2，铁匠 $3/'],
    [/^Mana Control ([\d\.,]+)\/([\d\.,]+), Productivity ([\d\.,]+)\/([\d\.,]+),$/, '法力控制 $1/$2，效率 $3/$4，'],
    [/^Mana Control ([\d\.,]+)\/([\d\.,]+), Meditation ([\d\.,]+)\/([\d\.,]+),$/, '法力控制 $1/$2，冥想 $3/$4，'],
    [/^Mana Control ([\d\.,]+)\/([\d\.,]+), Chairman ([\d\.,]+)\/$/, '法力控制 $1/$2，会长 $3/'],
    [/^Mana Control ([\d\.,]+)\/([\d\.,]+), Student ([\d\.,]+)\/$/, '法力控制 $1/$2，学生 $3/'],
    [/^Mana Control ([\d\.,]+)\/([\d\.,]+), Veteran Knight ([\d\.,]+)\/$/, '法力控制 $1/$2，资深骑士 $3/'],
    [/^Mana Control ([\d\.,]+)\/([\d\.,]+), Master Wizard ([\d\.,]+)\/$/, '法力控制 $1/$2，大法师 $3/'],
    [/^Mana Control ([\d\.,]+)\/([\d\.,]+), Adept Mage ([\d\.,]+)\/$/, '法力控制 $1/$2，熟练法师 $3/'],
    [/^Mana Control ([\d\.,]+)\/([\d\.,]+), Apprentice Mage ([\d\.,]+)\/$/, '法力控制 $1/$2，魔法学徒 $3/'],
    [/^Mana Control ([\d\.,]+)\/([\d\.,]+), Battle Tactics ([\d\.,]+)\/([\d\.,]+), Holy Knight ([\d\.,]+)\/$/, '法力控制 $1/$2，战斗战术 $3/$4，圣骑士 $5/'],
    [/^Mana Control ([\d\.,]+)\/([\d\.,]+), Meditation ([\d\.,]+)\/([\d\.,]+), Archmage ([\d\.,]+)\/$/, '法力控制 $1/$2，冥想 $3/$4，法宗 $5/'],
    [/^Mana Control ([\d\.,]+)\/([\d\.,]+), Productivity ([\d\.,]+)\/([\d\.,]+), Chronomancer ([\d\.,]+)\/$/, '法力控制 $1/$2，效率 $3/$4，时光法师 $5/'],
    [/^Fisherman ([\d\.,]+)\/$/, '渔民 $1/'],
    [/^Beggar ([\d\.,]+)\/$/, '乞丐 $1/'],
    [/^x(.+) Evil$/, 'x$1 邪恶'],
    [/^x(.+) Essence \+ Evil Gain$/, 'x$1 精华 + 邪恶收益'],
    [/^x(.+) Essence Gain$/, 'x$1 精华收益'],
    [/^x(.+) Evil Gain$/, 'x$1 邪恶收益'],
    [/^x(.+) Longer Lifespan$/, 'x$1 更长的寿命'],
    [/^x(.+) Military Pay$/, 'x$1 军队收入'],
    [/^x(.+) Gamespeed$/, 'x$1 游戏速度'],
    [/^x(.+) Max Lvl Multiplier$/, 'x$1 最高等级乘数'],
    [/^x(.+) Job Pay$/, 'x$1 工作收入'],
    [/^x(.+) Class Pay$/, 'x$1 课程收入'],
    [/^x(.+) Essence gain \+ x(.+) Hero XP$/, 'x$1 精华增益 + x$2英雄经验'],
    [/^x(.+) Hero XP$/, 'x$1 英雄经验'],
    [/^x(.+) Class XP$/, 'x$1 工作经验'],
    [/^x(.+) Time Warping$/, 'x$1 时间扭曲'],
    [/^x(.+) Evil gain$/, 'x$1 邪恶增益'],
    [/^x(.+) Essence gain$/, 'x$1 精华增益'],
    [/^x(.+) Essence gain \(increases over time, influenced by time warping\)$/, 'x$1 精华增益 （随时间增加，受时间扭曲影响）'],
    [/^x(.+) Longer lifespan$/, 'x$1 更长的寿命'],
    [/^x(.+) T.A.A. XP$/, 'x$1 奥术协会（T.A.A）工作经验'],
    [/^x(.+) T.A.A Pay$/, 'x$1 奥术协会（T.A.A）收入'],
    [/^x(.+) Ability XP$/, 'x$1 能力经验'],
    [/^x(.+) Fundamentals XP$/, 'x$1 基本原理经验'],
    [/^x(.+) Magic XP$/, 'x$1 魔法经验'],
    [/^x(.+) Chairman XP$/, 'x$1 会长经验'],
    [/^x(.+) Magical XP$/, 'x$1 魔法经验'],
    [/^x(.+) Dark Matter Gain$/, 'x$1 暗物质增益'],
    [/^x(.+) Merchant Pay$/, 'x$1 商人收入'],
    [/^x(.+) Farm upgrade$/, 'x$1 农场升级'],
    [/^x(.+) Blacksmith upgrade$/, 'x$1 铁匠升级'],
    [/^x(.+) Merchant upgrade$/, 'x$1 商人升级'],
    [/^x(.+) Fishing upgrade$/, 'x$1 钓鱼升级'],
    [/^x(.+) Mining upgrade$/, 'x$1 挖矿升级'],
    [/^x(.+) Galactic Council XP$/, 'x$1 银河委员会经验'],
    [/^x(.+) Void Manipulation XP$/, 'x$1 虚空操纵经验'],
    [/^x(.+) Discovery XP$/, 'x$1 发现经验'],
    [/^x(.+) Skill XP$/, 'x$1 全部技能经验'],
    [/^x(.+) Strength XP$/, 'x$1 力量经验'],
    [/^x(.+) Military XP$/, 'x$1 军队经验'],
    [/^x(.+) The Void XP$/, 'x$1 虚空经验'],
    [/^x(.+) Job XP$/, 'x$1 工作经验'],
    [/^x(.+) Reduced Expenses$/, 'x$1 降低商店费用'],
    [/^x(.+) Expenses$/, 'x$1 费用'],
    [/^x(.+) Increased Happiness$/, 'x$1 增加的幸福'],
    [/^x(.+) Happiness$/, 'x$1 幸福'],
    [/^x(.+) All XP$/, 'x$1 全部经验'],
    [/^Void Slave (.+), Chairman (.+)$/, '虚空奴隶 $1，会长 $2'],
    [/^(.+), Probation level (.+)$/, '$1，实习生等级 $2'],
    [/^(.+), Meditation level (.+), Productivity level (.+)$/, '$1，冥想等级 $2，效率等级 $3'],
    [/^(.+), Novel Knowledge level (.+)$/, '$1，新知识 $2'],
    [/^(.+), Master wizard level (.+)$/, '$1，大法师等级 $2'],
    [/^If you decide to embrace evil, all of your levels, coins and even max levels will be reset.\n(.+)You will be reborn as a fresh slate. However, you will unlock a new line of skills and gain$/, '如果你决定接受邪恶，那么你所有的关卡、金币甚至最高关卡都将被重置。你将以崭新的面貌重生。然而，你将解锁一个新的技能线和获得'],
    [/^Your gut instinct was right. The moment you hit the grand age of 200, you hear an ominous hum coming from the amulet.\n(.+)A mouth emerges from its surface and begins to cackle, and proceeds to say\: "So you've made it this far... Are you ready to embrace evil\?"$/, '你的直觉是对的。当你到达200岁的时候，你会听到护身符发出不祥的嗡嗡声。一张嘴从它的表面露出来，咯咯地笑着说\:“你已经走到这一步了……你准备好迎接邪恶了吗\?”'],
    [/^You stumble across a strange looking amulet on your 25th birthday. It does not look like\n(.+)it has any worth on the market given that it's made from cheap-looking copper. However, you\n(.+)feel a weird urge to keep the amulet, so you slip it into your pocket for safekeeping.$/, '在25岁生日那天，你碰巧发现了一个奇怪的护身符。这个护身符似乎是个不值钱的铜制品，看起来很廉价。但一种奇怪的冲动促使你想要保留这个护身符，所以你把它装进兜里留了下来。'],
    [/^Concentration level (.+)\/(.+), Meditation level (.+)\/$/, '专注等级 $1\/$2，冥想等级 $3\/'],
    [/^On your 65th birthday, you once again encounter the strange, unexplained shivering from your\n(.+)amulet. But this time, a living eyeball emerges from the centre. Although terribly frightened,\n(.+)you realise you do not have many years to live left anyway so you consider touching the eye\n(.+)to see what happens.$/, '在你65岁生日那天，护身符再次发出奇怪的、无法解释的颤动。而且，一个活生生的眼球从护身符的中心冒了出来！尽管你非常害怕，但你意识到你已时日无多，所以你尝试触摸这个眼球，看看会发生什么。'],
    [/^([\d\.]+)\/([\d\.]+), Veteran footman level (.+)\/$/, '$1\/$2, 资深步兵等级 $3\/'],
    [/^([\d\.]+)\/([\d\.]+), Blacksmith level (.+)\/$/, '$1\/$2, 铁匠等级 $3\/'],
    [/^([\d\.]+)\/([\d\.]+), Immortality level (.+)\/$/, '$1\/$2, 永生等级 $3\/'],
    [/^([\d\.]+)\/(.+), Mage level (.+)\/$/, '$1\/$2, 法师等级 $3\/'],
    [/^([\d\.]+)\/([\d\.]+), Footman level (.+)\/$/, '$1\/$2, 步兵等级 $3\/'],
    [/^([\d\.]+)\/([\d\.]+), Veteran knight level (.+)\/$/, '$1\/$2, 资深骑士等级 $3\/'],
    [/^([\d\.]+)\/([\d\.]+), Mana control level (.+)\/$/, '$1\/$2, 法力控制等级 $3\/'],
    [/^([\d\.]+)\/([\d\.]+), Battle tactics level (.+)\/$/, '$1\/$2, 战斗战术等级 $3\/'],
    [/^([\d\.]+)\/([\d\.]+), Holy knight level (.+)\/$/, '$1\/$2, 圣骑士等级 $3\/'],
    [/^([\d\.]+)\/([\d\.]+), Apprentice mage level (.+)\/$/, '$1\/$2, 魔法学徒等级 $3\/'],
    [/^([\d\.]+)\/([\d\.]+), Elite knight level (.+)\/$/, '$1\/$2, 精英骑士等级 $3\/'],
    [/^([\d\.]+)\/([\d\.]+), Student level (.+)\/$/, '$1\/$2, 学生等级 $3\/'],
    [/^([\d\.]+)\/([\d\.]+), Knight level (.+)\/$/, '$1\/$2, 骑士等级 $3\/'],
    [/^([\d\.]+)\/([\d\.]+), Miner level (.+)\/$/, '$1\/$2, 矿工等级 $3\/'],
    [/^([\d\.]+)\/([\d\.]+), Fisherman level (.+)\/$/, '$1\/$2, 渔夫等级 $3\/'],
    [/^([\d\.]+)\/([\d\.]+), Strength level (.+)\/$/, '$1\/$2, 力量等级 $3\/'],
    [/^([\d\.]+)k\/([\d\.]+)k, Dark influence level (.+)\/$/, '$1k\/$2k, 黑暗影响等级 $3\/'],
    [/^([\d\.]+)k\/([\d\.]+)k, Wizard level (.+)\/$/, '$1k\/$2k, 巫师等级 $3\/'],
    [/^([\d\.]+)k\/([\d\.]+)k, Chairman level (.+)\/$/, '$1k\/$2k, 会长等级 $3\/'],
    [/^([\d\.]+)k\/([\d\.]+)k, Evil control level (.+)\/$/, '$1k\/$2k, 邪恶控制等级 $3\/'],
    [/^([\d\.]+)k\/([\d\.]+)k, Intimidation level (.+)\/$/, '$1k\/$2k, 威胁等级 $3\/'],
    [/^([\d\.]+)k\/([\d\.]+)k, Time warping level (.+)\/$/, '$1k\/$2k, 时间扭曲等级 $3\/'],
    [/^([\d\.]+)\/([\d\.]+), Productivity level (\d+)\/$/, '$1\/$2, 效率等级 $3\/'],
    [/^([\d\.]+)\/([\d\.]+), Squire level (\d+)\/$/, '$1\/$2, 护卫等级 $3\/'],
    [/^([\d\.]+)\/([\d\.]+), Meditation level (\d+)\/$/, '$1\/$2, 冥想等级 $3\/'],
    [/^([\d\.]+) essence$/, '$1 精华'],
    [/^([\d\.]+) Dark Matter$/, '$1 暗物质'],
    [/^([\d\.]+) \+ the max level of the skill or job \/ (\d+).$/, '$1 \+ 你的技能或工作的最高等级 \/ $2。'],
    [/^On your 45th birthday, you feel the amulet shiver uncontrollably in your pocket. You take it\n(.+)out and the constant shivering suddenly stops. More to your bizarre surprise, you notice\n(.+)a strange etching on the centre of the amulet.$/, '在你45岁生日那天，你感到兜里的护身符毫无征兆地颤动起来。你拿起护身符，它却停止了颤动。持续的颤抖突然停止了。更让你惊讶的是，护身符的中心出现了一个奇怪的蚀刻印记。'],
    [/^By touching the eyeball, you will be reborn and have to restart life again, losing all your levels and coins.\n(.+)However, you will gain$/, '通过触摸眼球，你将获得重生，你将会失去所有等级和金币。然而,你会得到'],
    [/^法力控制等级 (.+)，战斗战术等级 (.+), Holy knight level (.+)\/$/, '法力控制等级 $1，战斗战术等级 $2, 圣骑士等级 $3\/'],
    [/^Mana control level (\d+)\/(\d+), Student level (\d+)\/$/, '法力控制等级 $1\/$2，学生等级 $3\/'],
    [/^Battle tactics level (\d+)\/(\d+), Knight level (\d+)\/$/, '战斗战术等级 $1\/$2，骑士等级 $3\/'],
    [/^Battle tactics level (\d+)\/(\d+), Footman level (\d+)\/$/, '战斗战术等级 $1\/$2，步兵等级 $3\/'],
    [/^Bargaining level (\d+)\/(\d+), Blacksmith level (\d+)\/$/, '议价等级 $1\/$2，铁匠等级 $3\/'],
    [/^(\d+)\/(\d+), Battle tactics level (.+)\/$/, '$1/$2，战斗战术等级 $3\/'],
    [/^(\d+)\/(\d+), Mage level (.+)\/$/, '$1/$2，法师等级 $3\/'],
    [/^(\d+)\/(\d+)k, Chairman level (.+)\/$/, '$1/$2k，会长等级 $3\/'],
    [/^(\d+)\/(.+), Battle tactics level (.+), Holy knight level (.+)\/$/, '$1/$2，战斗战术等级 $3，圣骑士等级 $4\/'],
    [/^(.+)\/(.+), Battle Tactics (.+),$/, '$1/$2，战斗战术 $3，'],
    [/^Mana Control (.+)\/(.+), Battle Tactics (.+),$/, '法力控制 $1/$2，战斗战术 $3，'],
    [/^([\d\.,]+) evil$/, '$1 邪恶'],
    [/^(.+) Dark Matter$/, '$1 暗物质'],
    [/^You have embraced evil$/, '你拥抱了邪恶'],
    [/^Embrace evil$/, '拥抱邪恶'],
    [/^(.+) evil$/, '$1 邪恶'],
    [/^(.+) essence$/, '$1 精华'],
    [/^([\d\.]+)e([\d\.,]+) evil$/, '$1e$2 邪恶'],
    [/^Age ([\d\.,]+) Day$/, '年龄: $1 岁，天数'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);